"""
Seed script for the Listening feature.

IMPORTANT: LESSONS currently contains only ONE short test lesson. Run this,
listen to the generated audio, and confirm quality and speech rate before
adding more lessons to the list and re-running for bulk generation.

Run:
    cd backend
    python scripts/seed_listening.py
"""
import os
import sys

# Allow importing from the backend root regardless of where the script is run from
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.database import SessionLocal
from app.models.models import ListeningAudio, ListeningQuestion
from app.services.listening_audio import generate_lesson_audio

DEFAULT_SPEAKER_NAMES = {"A": "Woman", "B": "Man"}

LESSONS = [
    {
        "slug": "test-cafe-order",
        "title": "Ordering at a Cafe",
        "level": "intermediate",
        "turns": [
            ("A", "Hi there, what can I get for you today?"),
            ("B", "I'd like a medium latte and a blueberry muffin, please."),
            ("A", "Sure. Would you like that for here or to go?"),
            ("B", "To go, thanks."),
        ],
        "questions": [
            {
                "type": "fill_blank",
                "prompt": "The customer orders a medium latte and a ____ muffin.",
                "options": None,
                "correct_answer": "blueberry",
                "order": 1,
            },
            {
                "type": "true_false",
                "prompt": "The customer is eating in the cafe.",
                "options": None,
                "correct_answer": "False",
                "order": 2,
            },
            {
                "type": "mcq",
                "prompt": "What size latte does the customer order?",
                "options": ["Small", "Medium", "Large"],
                "correct_answer": "Medium",
                "order": 3,
            },
        ],
    },
    {
        "slug": "supermarket-shopping",
        "title": "Shopping at the Supermarket",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Excuse me, can you help me?"),
            ("A", "Of course. What do you need?"),
            ("B", "Where is the milk?"),
            ("A", "The milk is in the dairy section, in aisle five at the back."),
            ("B", "Thank you. And where are the eggs?"),
            ("A", "The eggs are next to the milk, on the bottom shelf."),
            ("B", "Great. I also need rice and bread."),
            ("A", "Rice is in aisle three. Bread is near the entrance, on your left."),
            ("B", "Do you have any fresh fruit?"),
            ("A", "Yes, the fruit and vegetables are at the front of the store."),
            ("B", "Are the bananas on sale today?"),
            ("A", "Yes, they are cheap this week — one dollar a kilo."),
            ("B", "Good. Can I have a basket, please?"),
            ("A", "Of course. The baskets are by the door. The big trolleys are outside."),
            ("B", "A basket is fine, thank you. Okay, I have everything now."),
            ("A", "Great, let's go to the checkout. Did you find everything?"),
            ("B", "Yes, thank you."),
            ("A", "That's twenty-three dollars, please."),
            ("B", "Do you have a plastic bag?"),
            ("A", "Yes, but a bag costs ten cents."),
            ("B", "That's fine. One bag, please."),
            ("A", "Okay, twenty-three dollars and ten cents."),
            ("B", "Here is my card."),
            ("A", "Thank you. Here is your receipt. Please check the expiry date on the milk."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The milk is in aisle ___.", "options": None, "correct_answer": "five|5", "order": 1},
            {"type": "fill_blank", "prompt": "Bananas cost ___ dollar a kilo.", "options": None, "correct_answer": "one|1", "order": 2},
            {"type": "fill_blank", "prompt": "A plastic bag costs ___ cents.", "options": None, "correct_answer": "ten|10", "order": 3},
            {"type": "fill_blank", "prompt": "The total is ___ dollars and ten cents.", "options": None, "correct_answer": "twenty-three|23", "order": 4},
            {"type": "fill_blank", "prompt": "The customer also needs rice and ___.", "options": None, "correct_answer": "bread", "order": 5},
            {"type": "true_false", "prompt": "The eggs are next to the milk.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "The bananas are expensive this week.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The customer takes a big trolley.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The bread is near the entrance.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer pays with cash.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Where is the bread?", "options": ["at the back", "near the entrance", "in aisle five"], "correct_answer": "near the entrance", "order": 11},
            {"type": "mcq", "prompt": "How does the customer pay?", "options": ["cash", "card", "phone"], "correct_answer": "card", "order": 12},
            {"type": "mcq", "prompt": "What should the customer check?", "options": ["the receipt total", "the expiry date on the milk", "the address"], "correct_answer": "the expiry date on the milk", "order": 13},
            {"type": "mcq", "prompt": "Where are the fruit and vegetables?", "options": ["at the front", "in aisle three", "at the back"], "correct_answer": "at the front", "order": 14},
            {"type": "mcq", "prompt": "The eggs are on the ___ shelf.", "options": ["top", "middle", "bottom"], "correct_answer": "bottom", "order": 15},
        ],
    },
    {
        "slug": "asking-directions",
        "title": "Asking for Directions",
        "level": "beginner",
        "speaker_names": {"A": "Local", "B": "Visitor"},
        "turns": [
            ("B", "Excuse me, can you help me?"),
            ("A", "Sure. What are you looking for?"),
            ("B", "How do I get to the train station?"),
            ("A", "It's not far. Go straight down this street."),
            ("B", "Okay, go straight. And then?"),
            ("A", "Then turn left at the traffic lights."),
            ("B", "Turn left at the traffic lights. Okay."),
            ("A", "Yes. Walk past the bank, and the station is on your right."),
            ("B", "It's on my right. Is it far?"),
            ("A", "No, it's about five minutes on foot."),
            ("B", "Great. Is there a pharmacy near here too?"),
            ("A", "Yes. Go back to the traffic lights and turn right."),
            ("B", "Turn right at the traffic lights."),
            ("A", "Yes. The pharmacy is next to the supermarket, on the corner."),
            ("B", "Next to the supermarket, on the corner. Okay."),
            ("A", "It's opposite the post office. You can't miss it."),
            ("B", "Is it open now?"),
            ("A", "Yes, it's open until nine."),
            ("B", "One more thing. Where is the nearest bus stop?"),
            ("A", "The bus stop is across the road, in front of the café."),
            ("B", "Across the road, in front of the café. Which bus goes to the city centre?"),
            ("A", "Take bus number ten. It comes every fifteen minutes."),
            ("B", "Bus number ten. Thank you so much. You are very kind."),
            ("A", "You're welcome. If you get lost, just ask someone again. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "To reach the station, turn left at the ___.", "options": None, "correct_answer": "traffic lights", "order": 1},
            {"type": "fill_blank", "prompt": "The station is about ___ minutes on foot.", "options": None, "correct_answer": "five|5", "order": 2},
            {"type": "fill_blank", "prompt": "The pharmacy is next to the ___.", "options": None, "correct_answer": "supermarket", "order": 3},
            {"type": "fill_blank", "prompt": "Take bus number ___ to the city centre.", "options": None, "correct_answer": "ten|10", "order": 4},
            {"type": "fill_blank", "prompt": "The bus comes every ___ minutes.", "options": None, "correct_answer": "fifteen|15", "order": 5},
            {"type": "true_false", "prompt": "The train station is very far.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The pharmacy is opposite the post office.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The pharmacy is closed now.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The bus stop is across the road.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The pharmacy is next to the café.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "How do you get to the station?", "options": ["go straight then turn left", "turn right immediately", "go back"], "correct_answer": "go straight then turn left", "order": 11},
            {"type": "mcq", "prompt": "The station is on the visitor's:", "options": ["left", "right", "corner"], "correct_answer": "right", "order": 12},
            {"type": "mcq", "prompt": "Where is the pharmacy?", "options": ["on the corner", "inside the station", "next to the bank"], "correct_answer": "on the corner", "order": 13},
            {"type": "mcq", "prompt": "The bus stop is in front of the:", "options": ["bank", "café", "post office"], "correct_answer": "café", "order": 14},
            {"type": "mcq", "prompt": "How often does bus ten come?", "options": ["every 5 minutes", "every 10 minutes", "every 15 minutes"], "correct_answer": "every 15 minutes", "order": 15},
        ],
    },
    {
        "slug": "buying-a-train-ticket",
        "title": "Buying a Train Ticket",
        "level": "beginner",
        "speaker_names": {"A": "Clerk", "B": "Traveller"},
        "turns": [
            ("B", "Hello. I'd like a ticket to Manchester, please."),
            ("A", "Single or return?"),
            ("B", "A return, please. What time is the next train?"),
            ("A", "The next train leaves at ten thirty."),
            ("B", "And how much is a return ticket?"),
            ("A", "It's twenty-five dollars."),
            ("B", "Okay. Which platform is it?"),
            ("A", "Platform four. Go up the stairs and turn right."),
            ("B", "How long is the journey?"),
            ("A", "About two hours. You arrive at half past twelve."),
            ("B", "Is it a direct train?"),
            ("A", "No, you change at Birmingham. Don't worry, you have twenty minutes."),
            ("B", "Do I need to book a seat?"),
            ("A", "No, you don't need to. The train is not busy today."),
            ("B", "Can I pay by card?"),
            ("A", "Yes, card or cash. Both are fine."),
            ("B", "Here is my card."),
            ("A", "Thank you. Here is your ticket. Keep it safe — you need it on the train."),
            ("B", "One more question. Where can I buy a coffee?"),
            ("A", "There is a small shop next to platform two."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good trip!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The traveller wants a ticket to ___.", "options": None, "correct_answer": "Manchester", "order": 1},
            {"type": "fill_blank", "prompt": "The next train leaves at ___ thirty.", "options": None, "correct_answer": "ten|10", "order": 2},
            {"type": "fill_blank", "prompt": "A return ticket costs ___ dollars.", "options": None, "correct_answer": "twenty-five|25", "order": 3},
            {"type": "fill_blank", "prompt": "The train leaves from platform ___.", "options": None, "correct_answer": "four|4", "order": 4},
            {"type": "fill_blank", "prompt": "The traveller changes trains at ___.", "options": None, "correct_answer": "Birmingham", "order": 5},
            {"type": "true_false", "prompt": "The traveller buys a single ticket.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The journey takes about two hours.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "It is a direct train.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The traveller needs to book a seat.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The traveller can pay by card.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What kind of ticket does the traveller buy?", "options": ["single", "return", "weekly"], "correct_answer": "return", "order": 11},
            {"type": "mcq", "prompt": "To find the platform, go up the stairs and turn:", "options": ["left", "right", "back"], "correct_answer": "right", "order": 12},
            {"type": "mcq", "prompt": "What time does the train arrive?", "options": ["ten thirty", "half past twelve", "two o'clock"], "correct_answer": "half past twelve", "order": 13},
            {"type": "mcq", "prompt": "How long does the traveller wait at Birmingham?", "options": ["ten minutes", "twenty minutes", "two hours"], "correct_answer": "twenty minutes", "order": 14},
            {"type": "mcq", "prompt": "Where can the traveller buy a coffee?", "options": ["on the train", "next to platform two", "at platform four"], "correct_answer": "next to platform two", "order": 15},
        ],
    },
    {
        "slug": "buying-clothes",
        "title": "Buying Clothes",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Excuse me, do you have this shirt in a medium?"),
            ("A", "Let me check. Yes, here is a medium. What colour would you like?"),
            ("B", "Do you have it in blue?"),
            ("A", "Yes, we have blue, white, and black."),
            ("B", "I'd like the blue one, please. Can I try it on?"),
            ("A", "Of course. The fitting room is over there, on the left."),
            ("B", "Thank you. Excuse me, it's a little too big. Do you have a small?"),
            ("A", "Yes, here is a small. Try this one."),
            ("B", "This one is perfect. How much is it?"),
            ("A", "It's thirty dollars. But today there is a discount — twenty percent off."),
            ("B", "So how much do I pay?"),
            ("A", "Twenty-four dollars."),
            ("B", "Great. I'll take it. Do you have these shoes in size eight?"),
            ("A", "I'm sorry, size eight is sold out. We have size nine."),
            ("B", "No, thank you. Just the shirt then."),
            ("A", "Okay. Would you like a bag?"),
            ("B", "Yes, please."),
            ("A", "That's twenty-four dollars. How would you like to pay?"),
            ("B", "By card, please. Can I return it if it doesn't fit?"),
            ("A", "Yes, you can return it in fourteen days. Keep the receipt."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a nice day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants the shirt in the colour ___.", "options": None, "correct_answer": "blue", "order": 1},
            {"type": "fill_blank", "prompt": "The shirt costs ___ dollars before the discount.", "options": None, "correct_answer": "thirty|30", "order": 2},
            {"type": "fill_blank", "prompt": "The discount is ___ percent off.", "options": None, "correct_answer": "twenty|20", "order": 3},
            {"type": "fill_blank", "prompt": "After the discount, the customer pays ___ dollars.", "options": None, "correct_answer": "twenty-four|24", "order": 4},
            {"type": "fill_blank", "prompt": "The customer can return the shirt in ___ days.", "options": None, "correct_answer": "fourteen|14", "order": 5},
            {"type": "true_false", "prompt": "The medium shirt is too small.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The fitting room is on the left.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The shoes in size eight are available.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer pays by card.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer must keep the receipt to return the shirt.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Which size fits the customer?", "options": ["medium", "small", "large"], "correct_answer": "small", "order": 11},
            {"type": "mcq", "prompt": "What colours does the shop have?", "options": ["blue white black", "red green", "only blue"], "correct_answer": "blue white black", "order": 12},
            {"type": "mcq", "prompt": "Why is the shirt cheaper today?", "options": ["it is old", "there is a discount", "it is damaged"], "correct_answer": "there is a discount", "order": 13},
            {"type": "mcq", "prompt": "What size shoes does the customer want?", "options": ["eight", "nine", "ten"], "correct_answer": "eight", "order": 14},
            {"type": "mcq", "prompt": "What does the customer buy?", "options": ["shirt and shoes", "only the shirt", "only shoes"], "correct_answer": "only the shirt", "order": 15},
        ],
    },
    {
        "slug": "meeting-a-new-neighbour",
        "title": "Meeting a New Neighbour",
        "level": "beginner",
        "speaker_names": {"A": "Neighbour", "B": "New resident"},
        "turns": [
            ("A", "Hello! Are you the new neighbour?"),
            ("B", "Yes, hello. I moved in yesterday. My name is Ben."),
            ("A", "Nice to meet you, Ben. I'm Susan. I live in number ten."),
            ("B", "Nice to meet you too, Susan."),
            ("A", "Where are you from?"),
            ("B", "I'm from Thailand. I came here last month."),
            ("A", "Welcome! How do you like the area?"),
            ("B", "It's very nice. But I don't know many places yet."),
            ("A", "Don't worry. There is a good supermarket near here. It opens at eight."),
            ("B", "That's good to know. Is there a park nearby?"),
            ("A", "Yes, there is a park at the end of the street. It's very quiet."),
            ("B", "Great. I have a small dog. Is that okay here?"),
            ("A", "Yes, many people have pets. Dogs are welcome."),
            ("B", "Good. What day is rubbish collection?"),
            ("A", "The rubbish truck comes on Wednesday morning. Put your bins outside on Tuesday night."),
            ("B", "Wednesday morning. Thank you."),
            ("A", "If you need anything, just knock on my door."),
            ("B", "Thank you, Susan. You are very kind."),
            ("A", "No problem. Welcome to the street, Ben!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The new resident's name is ___.", "options": None, "correct_answer": "Ben", "order": 1},
            {"type": "fill_blank", "prompt": "The neighbour's name is ___.", "options": None, "correct_answer": "Susan", "order": 2},
            {"type": "fill_blank", "prompt": "The new resident is from ___.", "options": None, "correct_answer": "Thailand", "order": 3},
            {"type": "fill_blank", "prompt": "The supermarket opens at ___.", "options": None, "correct_answer": "eight|8", "order": 4},
            {"type": "fill_blank", "prompt": "Rubbish collection is on ___ morning.", "options": None, "correct_answer": "Wednesday", "order": 5},
            {"type": "true_false", "prompt": "Ben moved in last week.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "There is a park at the end of the street.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Pets are not allowed on the street.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "Susan lives in number ten.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Ben has a cat.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "When did Ben move in?", "options": ["yesterday", "last week", "last year"], "correct_answer": "yesterday", "order": 11},
            {"type": "mcq", "prompt": "Where is the park?", "options": ["at the end of the street", "next to the supermarket", "far away"], "correct_answer": "at the end of the street", "order": 12},
            {"type": "mcq", "prompt": "What pet does Ben have?", "options": ["a cat", "a small dog", "a bird"], "correct_answer": "a small dog", "order": 13},
            {"type": "mcq", "prompt": "When should Ben put the bins outside?", "options": ["Wednesday morning", "Tuesday night", "Monday"], "correct_answer": "Tuesday night", "order": 14},
            {"type": "mcq", "prompt": "What does Susan say if Ben needs help?", "options": ["call the office", "knock on her door", "send a letter"], "correct_answer": "knock on her door", "order": 15},
        ],
    },
    {
        "slug": "at-the-post-office",
        "title": "At the Post Office",
        "level": "beginner",
        "speaker_names": {"A": "Clerk", "B": "Customer"},
        "turns": [
            ("B", "Hello. I want to send this letter to Canada."),
            ("A", "Okay. Put it on the scale, please. It's twenty grams."),
            ("B", "How much is it?"),
            ("A", "To Canada, it's two dollars."),
            ("B", "Okay. I also want to send this box to my family."),
            ("A", "Where to?"),
            ("B", "To Thailand."),
            ("A", "Put the box on the scale. It's three kilos. That's fifteen dollars."),
            ("B", "How long does it take?"),
            ("A", "The letter takes one week. The box takes about two weeks."),
            ("B", "Is there a faster way for the box?"),
            ("A", "Yes, express post takes five days, but it costs twenty-five dollars."),
            ("B", "No, two weeks is fine. The normal way, please."),
            ("A", "Okay. Do you want to track the box?"),
            ("B", "Yes, please. What is tracking?"),
            ("A", "You get a number. You can check where the box is online."),
            ("B", "Great. I'll take it."),
            ("A", "Okay. Two dollars for the letter, fifteen for the box. Seventeen dollars in total."),
            ("B", "Here is twenty dollars."),
            ("A", "Thank you. Here is your change — three dollars — and your tracking number. Keep it safe."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer sends a letter to ___.", "options": None, "correct_answer": "Canada", "order": 1},
            {"type": "fill_blank", "prompt": "The letter costs ___ dollars.", "options": None, "correct_answer": "two|2", "order": 2},
            {"type": "fill_blank", "prompt": "The box weighs ___ kilos.", "options": None, "correct_answer": "three|3", "order": 3},
            {"type": "fill_blank", "prompt": "The box costs ___ dollars.", "options": None, "correct_answer": "fifteen|15", "order": 4},
            {"type": "fill_blank", "prompt": "The total is ___ dollars.", "options": None, "correct_answer": "seventeen|17", "order": 5},
            {"type": "true_false", "prompt": "The letter goes to Thailand.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The box takes about two weeks.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Express post is cheaper than normal post.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer wants to track the box.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer pays with a twenty-dollar note.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Where does the box go?", "options": ["Canada", "Thailand", "Japan"], "correct_answer": "Thailand", "order": 11},
            {"type": "mcq", "prompt": "How long does the letter take?", "options": ["one week", "two weeks", "five days"], "correct_answer": "one week", "order": 12},
            {"type": "mcq", "prompt": "How much is express post for the box?", "options": ["fifteen dollars", "twenty dollars", "twenty-five dollars"], "correct_answer": "twenty-five dollars", "order": 13},
            {"type": "mcq", "prompt": "What does the customer get to track the box?", "options": ["a receipt", "a number", "an email"], "correct_answer": "a number", "order": 14},
            {"type": "mcq", "prompt": "How much change does the customer get?", "options": ["two dollars", "three dollars", "five dollars"], "correct_answer": "three dollars", "order": 15},
        ],
    },
    {
        "slug": "making-weekend-plans",
        "title": "Making Weekend Plans",
        "level": "beginner",
        "speaker_names": {"A": "Mia", "B": "Tom"},
        "turns": [
            ("A", "Hi Tom! Are you free this weekend?"),
            ("B", "Hi Mia! Yes, I think so. Why?"),
            ("A", "Do you want to go to the cinema?"),
            ("B", "Sure! What film do you want to see?"),
            ("A", "There is a new action film. It looks really good."),
            ("B", "Nice. What day is good for you?"),
            ("A", "Saturday or Sunday. I don't mind."),
            ("B", "Let's go on Saturday. I'm busy on Sunday."),
            ("A", "Okay, Saturday. What time?"),
            ("B", "How about the afternoon? Maybe two o'clock?"),
            ("A", "Two is perfect. But the film is quite long. It finishes at four thirty."),
            ("B", "That's fine. Actually, do you want to have lunch first?"),
            ("A", "Good idea! Let's meet at twelve for lunch, then the film."),
            ("B", "Great. Where do you want to eat?"),
            ("A", "There is a nice pizza place near the cinema."),
            ("B", "I love pizza! Let's go there."),
            ("A", "Perfect. By the way, can you bring your sister?"),
            ("B", "Sure, she likes films too. She can come."),
            ("A", "Wonderful. See you on Saturday at twelve!"),
            ("B", "See you then. Have a good week!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "They want to go to the ___.", "options": None, "correct_answer": "cinema", "order": 1},
            {"type": "fill_blank", "prompt": "They decide to go on ___.", "options": None, "correct_answer": "Saturday", "order": 2},
            {"type": "fill_blank", "prompt": "They will meet at ___ o'clock for lunch.", "options": None, "correct_answer": "twelve|12", "order": 3},
            {"type": "fill_blank", "prompt": "The film finishes at ___ thirty.", "options": None, "correct_answer": "four|4", "order": 4},
            {"type": "fill_blank", "prompt": "They will eat at a ___ place.", "options": None, "correct_answer": "pizza", "order": 5},
            {"type": "true_false", "prompt": "Tom is busy on Sunday.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "They will see a comedy film.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "They will have lunch after the film.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The pizza place is near the cinema.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Tom's sister will come too.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What do they want to watch?", "options": ["an action film", "a comedy", "a cartoon"], "correct_answer": "an action film", "order": 11},
            {"type": "mcq", "prompt": "Why not Sunday?", "options": ["the cinema is closed", "Tom is busy", "Mia is busy"], "correct_answer": "Tom is busy", "order": 12},
            {"type": "mcq", "prompt": "What time is the film?", "options": ["twelve", "two", "four thirty"], "correct_answer": "two", "order": 13},
            {"type": "mcq", "prompt": "What do they do before the film?", "options": ["shopping", "have lunch", "go home"], "correct_answer": "have lunch", "order": 14},
            {"type": "mcq", "prompt": "Who else will come?", "options": ["Tom's brother", "Tom's sister", "Mia's friend"], "correct_answer": "Tom's sister", "order": 15},
        ],
    },
    {
        "slug": "calling-your-parents",
        "title": "Calling Your Parents",
        "level": "beginner",
        "speaker_names": {"A": "Mum", "B": "Child"},
        "turns": [
            ("B", "Hi Mum! How are you?"),
            ("A", "Hello! I'm fine, thank you. How are you? Are you eating well?"),
            ("B", "Yes, Mum. Don't worry. I cook every day."),
            ("A", "Good. And how is your new job?"),
            ("B", "It's good. My boss is very kind, and I like my colleagues."),
            ("A", "I'm so happy. Is it cold there?"),
            ("B", "Yes, it's a little cold now. But I have a warm coat."),
            ("A", "Good. Remember to wear a scarf. How is your friend, Lily?"),
            ("B", "She is fine. We meet every weekend."),
            ("A", "That's nice. You are not alone, then."),
            ("B", "No, I'm okay. How is Dad?"),
            ("A", "He is fine. He is in the garden now. He misses you."),
            ("B", "I miss him too. Actually, I have good news, Mum."),
            ("A", "Oh? What is it?"),
            ("B", "I passed my English test!"),
            ("A", "That's wonderful! I'm so proud of you."),
            ("B", "Thank you, Mum. By the way, can we video call on Sunday?"),
            ("A", "Of course! Sunday evening is good for me."),
            ("B", "Perfect. I will call at seven, your time."),
            ("A", "Okay. Take care of yourself. We love you."),
            ("B", "I love you too. Talk to you on Sunday. Bye!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The child cooks ___ day.", "options": None, "correct_answer": "every", "order": 1},
            {"type": "fill_blank", "prompt": "The child's new ___ is very kind.", "options": None, "correct_answer": "boss", "order": 2},
            {"type": "fill_blank", "prompt": "The weather there is a little ___.", "options": None, "correct_answer": "cold", "order": 3},
            {"type": "fill_blank", "prompt": "The child's friend's name is ___.", "options": None, "correct_answer": "Lily", "order": 4},
            {"type": "fill_blank", "prompt": "They will video call on ___.", "options": None, "correct_answer": "Sunday", "order": 5},
            {"type": "true_false", "prompt": "The child does not cook.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The child likes the colleagues.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Dad is in the garden.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The child failed the English test.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The video call is on Sunday evening.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How is the new job?", "options": ["bad", "good", "boring"], "correct_answer": "good", "order": 11},
            {"type": "mcq", "prompt": "What does Mum tell the child to wear?", "options": ["a hat", "a scarf", "gloves"], "correct_answer": "a scarf", "order": 12},
            {"type": "mcq", "prompt": "What good news does the child share?", "options": ["a new job", "passed the English test", "a new house"], "correct_answer": "passed the English test", "order": 13},
            {"type": "mcq", "prompt": "Where is Dad?", "options": ["at work", "in the garden", "sleeping"], "correct_answer": "in the garden", "order": 14},
            {"type": "mcq", "prompt": "What time will the child call on Sunday?", "options": ["seven", "eight", "nine"], "correct_answer": "seven", "order": 15},
        ],
    },
    {
        "slug": "cooking-dinner-together",
        "title": "Cooking Dinner Together",
        "level": "beginner",
        "speaker_names": {"A": "Partner A", "B": "Partner B"},
        "turns": [
            ("A", "I'm hungry. What do you want to eat tonight?"),
            ("B", "I don't know. What do we have in the fridge?"),
            ("A", "Let me see. We have eggs, tomatoes, and some cheese."),
            ("B", "We can make an omelette. Do we have any onions?"),
            ("A", "Yes, there are two onions here. And some bread."),
            ("B", "Perfect. Let's make a cheese omelette with bread."),
            ("A", "Good idea. But we don't have any milk."),
            ("B", "That's okay. We don't need milk for an omelette."),
            ("A", "Okay. Can you cut the tomatoes and onions?"),
            ("B", "Sure. And can you break the eggs?"),
            ("A", "Yes. How many eggs? Four?"),
            ("B", "Four is good. Two for you and two for me."),
            ("A", "Okay. Where is the salt?"),
            ("B", "It's next to the stove, on the right."),
            ("A", "Got it. Actually, do you want some tea after dinner?"),
            ("B", "Yes please. By the way, the rice is finished. We need to buy more tomorrow."),
            ("A", "Okay, I'll write it on the list. Anything else?"),
            ("B", "Yes, milk and onions. We are nearly out."),
            ("A", "Good. The omelette smells nice already!"),
            ("B", "I'm so hungry. Let's eat!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "They decide to make a cheese ___.", "options": None, "correct_answer": "omelette", "order": 1},
            {"type": "fill_blank", "prompt": "There are ___ onions in the kitchen.", "options": None, "correct_answer": "two|2", "order": 2},
            {"type": "fill_blank", "prompt": "They will use ___ eggs.", "options": None, "correct_answer": "four|4", "order": 3},
            {"type": "fill_blank", "prompt": "The salt is next to the ___.", "options": None, "correct_answer": "stove", "order": 4},
            {"type": "fill_blank", "prompt": "They need to buy more ___ tomorrow.", "options": None, "correct_answer": "rice", "order": 5},
            {"type": "true_false", "prompt": "They have milk in the fridge.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "They need milk for the omelette.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "They will have tea after dinner.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "There is bread in the kitchen.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "They will buy milk and onions tomorrow.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What do they decide to cook?", "options": ["rice", "a cheese omelette", "soup"], "correct_answer": "a cheese omelette", "order": 11},
            {"type": "mcq", "prompt": "How many eggs do they use?", "options": ["two", "three", "four"], "correct_answer": "four", "order": 12},
            {"type": "mcq", "prompt": "Where is the salt?", "options": ["in the fridge", "next to the stove", "on the table"], "correct_answer": "next to the stove", "order": 13},
            {"type": "mcq", "prompt": "What do they want after dinner?", "options": ["coffee", "tea", "juice"], "correct_answer": "tea", "order": 14},
            {"type": "mcq", "prompt": "What is finished and needs buying?", "options": ["bread", "rice", "cheese"], "correct_answer": "rice", "order": 15},
        ],
    },
    {
        "slug": "ordering-at-a-restaurant",
        "title": "Ordering at a Restaurant",
        "level": "beginner",
        "speaker_names": {"A": "Waiter", "B": "Customer"},
        "turns": [
            ("A", "Good evening. A table for how many?"),
            ("B", "For two, please."),
            ("A", "This way, please. Here is the menu."),
            ("B", "Thank you. Can we have some water first?"),
            ("A", "Of course. Still or sparkling?"),
            ("B", "Still, please. Okay, we are ready to order."),
            ("A", "Great. What would you like?"),
            ("B", "I'd like the chicken soup to start, and then the fish."),
            ("A", "Good choice. And for your friend?"),
            ("B", "She wants a salad and the pasta."),
            ("A", "Would you like anything to drink?"),
            ("B", "Two orange juices, please. Actually, make one apple juice."),
            ("A", "One orange and one apple. No problem."),
            ("B", "Is the fish spicy?"),
            ("A", "No, it's not spicy. But the pasta is a little spicy."),
            ("B", "That's fine. She likes spicy food."),
            ("A", "Perfect. Your food will be ready in about fifteen minutes."),
            ("B", "Thank you. By the way, do you have any vegetarian dishes?"),
            ("A", "Yes, the salad and the vegetable soup are vegetarian."),
            ("B", "Good to know. Can we have the bill together at the end?"),
            ("A", "Of course. I'll bring everything now."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Enjoy your meal!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants a table for ___.", "options": None, "correct_answer": "two|2", "order": 1},
            {"type": "fill_blank", "prompt": "To start, the customer orders chicken ___.", "options": None, "correct_answer": "soup", "order": 2},
            {"type": "fill_blank", "prompt": "The food will be ready in about ___ minutes.", "options": None, "correct_answer": "fifteen|15", "order": 3},
            {"type": "fill_blank", "prompt": "The customer changes one drink to ___ juice.", "options": None, "correct_answer": "apple", "order": 4},
            {"type": "fill_blank", "prompt": "The friend orders a salad and the ___.", "options": None, "correct_answer": "pasta", "order": 5},
            {"type": "true_false", "prompt": "The customer orders sparkling water.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The fish is spicy.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The pasta is a little spicy.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The salad is vegetarian.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer wants the bill at the end.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How many people are at the table?", "options": ["one", "two", "three"], "correct_answer": "two", "order": 11},
            {"type": "mcq", "prompt": "What does the customer order to eat?", "options": ["soup and fish", "salad and pasta", "only fish"], "correct_answer": "soup and fish", "order": 12},
            {"type": "mcq", "prompt": "What does the friend like?", "options": ["sweet food", "spicy food", "cold food"], "correct_answer": "spicy food", "order": 13},
            {"type": "mcq", "prompt": "Which dishes are vegetarian?", "options": ["salad and vegetable soup", "fish and pasta", "chicken soup"], "correct_answer": "salad and vegetable soup", "order": 14},
            {"type": "mcq", "prompt": "When does the customer want the bill?", "options": ["before the food", "together at the end", "with each dish"], "correct_answer": "together at the end", "order": 15},
        ],
    },
    {
        "slug": "booking-a-table-by-phone",
        "title": "Booking a Table by Phone",
        "level": "beginner",
        "speaker_names": {"A": "Staff", "B": "Caller"},
        "turns": [
            ("A", "Hello, Garden Restaurant. How can I help you?"),
            ("B", "Hello. I'd like to book a table, please."),
            ("A", "Of course. For which day?"),
            ("B", "For this Friday evening."),
            ("A", "And what time?"),
            ("B", "At seven o'clock. Is that okay?"),
            ("A", "Let me check. Yes, seven o'clock is fine. For how many people?"),
            ("B", "For four people."),
            ("A", "A table for four at seven on Friday. Can I have your name?"),
            ("B", "Yes, my name is David Lee."),
            ("A", "Thank you, Mr Lee. Do you want a table inside or outside?"),
            ("B", "Outside, please. But if it rains, inside is fine."),
            ("A", "No problem. Actually, the weather is nice this week."),
            ("B", "Good. What time do you close?"),
            ("A", "We close at eleven. The kitchen closes at ten."),
            ("B", "Okay. Are you open on Mondays?"),
            ("A", "No, we are closed on Mondays. We open from Tuesday to Sunday."),
            ("B", "Good to know. By the way, do you have parking?"),
            ("A", "Yes, there is free parking behind the restaurant."),
            ("B", "Perfect. Thank you very much."),
            ("A", "You're welcome, Mr Lee. See you on Friday!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The caller wants to book a table for ___ people.", "options": None, "correct_answer": "four|4", "order": 1},
            {"type": "fill_blank", "prompt": "The booking is for ___ evening.", "options": None, "correct_answer": "Friday", "order": 2},
            {"type": "fill_blank", "prompt": "The table is booked at ___ o'clock.", "options": None, "correct_answer": "seven|7", "order": 3},
            {"type": "fill_blank", "prompt": "The caller's name is David ___.", "options": None, "correct_answer": "Lee", "order": 4},
            {"type": "fill_blank", "prompt": "The restaurant closes at ___.", "options": None, "correct_answer": "eleven|11", "order": 5},
            {"type": "true_false", "prompt": "The caller wants a table inside.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The kitchen closes at ten.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The restaurant is open on Mondays.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "There is free parking behind the restaurant.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The restaurant opens from Tuesday to Sunday.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How many people is the table for?", "options": ["two", "four", "six"], "correct_answer": "four", "order": 11},
            {"type": "mcq", "prompt": "Where does the caller want to sit?", "options": ["inside", "outside", "at the bar"], "correct_answer": "outside", "order": 12},
            {"type": "mcq", "prompt": "What time does the kitchen close?", "options": ["ten", "eleven", "seven"], "correct_answer": "ten", "order": 13},
            {"type": "mcq", "prompt": "When is the restaurant closed?", "options": ["Sundays", "Mondays", "Fridays"], "correct_answer": "Mondays", "order": 14},
            {"type": "mcq", "prompt": "Where is the parking?", "options": ["in front", "behind the restaurant", "across the road"], "correct_answer": "behind the restaurant", "order": 15},
        ],
    },
    {
        "slug": "buying-a-sim-card",
        "title": "Buying a SIM Card",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Hello. I need a SIM card for my phone."),
            ("A", "Sure. Are you a visitor or do you live here?"),
            ("B", "I live here now. I just moved last month."),
            ("A", "Okay. Do you want a monthly plan or pay as you go?"),
            ("B", "What is the difference?"),
            ("A", "With a monthly plan, you pay every month. Pay as you go, you only pay when you use it."),
            ("B", "I think a monthly plan is better. How much is it?"),
            ("A", "This plan is twenty dollars a month. You get lots of data, calls, and texts."),
            ("B", "That sounds good. Do I need my passport?"),
            ("A", "Yes, please. I need to see your ID."),
            ("B", "Here is my passport."),
            ("A", "Thank you. Actually, do you have an address here?"),
            ("B", "Yes, here is a letter with my address."),
            ("A", "Perfect. The SIM card is free with this plan."),
            ("B", "Great. How long does it take to work?"),
            ("A", "It works in about one hour. But sometimes it is faster."),
            ("B", "Okay. Can I keep my old phone number?"),
            ("A", "Yes, but you need to bring a letter from your old company."),
            ("B", "I don't have it now. I'll get a new number then."),
            ("A", "No problem. Here is your new SIM card and your number."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Enjoy your new plan!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer needs a SIM card for their ___.", "options": None, "correct_answer": "phone", "order": 1},
            {"type": "fill_blank", "prompt": "The monthly plan costs ___ dollars a month.", "options": None, "correct_answer": "twenty|20", "order": 2},
            {"type": "fill_blank", "prompt": "The assistant needs to see the customer's ___.", "options": None, "correct_answer": "passport", "order": 3},
            {"type": "fill_blank", "prompt": "The SIM card works in about one ___.", "options": None, "correct_answer": "hour", "order": 4},
            {"type": "fill_blank", "prompt": "To keep the old number, the customer needs a letter from the old ___.", "options": None, "correct_answer": "company", "order": 5},
            {"type": "true_false", "prompt": "The customer is just a visitor.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The SIM card is free with the plan.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The customer chooses pay as you go.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer keeps the old phone number.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The plan includes data, calls, and texts.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Which plan does the customer choose?", "options": ["monthly plan", "pay as you go", "no plan"], "correct_answer": "monthly plan", "order": 11},
            {"type": "mcq", "prompt": "What does the customer show as ID?", "options": ["a driving licence", "a passport", "a bank card"], "correct_answer": "a passport", "order": 12},
            {"type": "mcq", "prompt": "How long does the SIM take to work?", "options": ["one hour", "one day", "one week"], "correct_answer": "one hour", "order": 13},
            {"type": "mcq", "prompt": "What does the customer need to keep the old number?", "options": ["a passport", "a letter from the old company", "money"], "correct_answer": "a letter from the old company", "order": 14},
            {"type": "mcq", "prompt": "What does the customer decide about the number?", "options": ["keep the old one", "get a new one", "use two numbers"], "correct_answer": "get a new one", "order": 15},
        ],
    },
]


def build_transcript(turns: list[tuple[str, str]], speaker_names: dict[str, str]) -> str:
    return "\n".join(f"{speaker_names[speaker]}: {text}" for speaker, text in turns)


def main() -> None:
    db = SessionLocal()
    try:
        existing_titles = {a.title for a in db.query(ListeningAudio).all()}

        for lesson in LESSONS:
            if lesson["title"] in existing_titles:
                print(f"--- Skipping '{lesson['slug']}' (already seeded) ---")
                continue

            print(f"--- Generating audio for '{lesson['slug']}' (level={lesson['level']}) ---")
            audio_url = generate_lesson_audio(lesson["turns"], lesson["slug"], lesson["level"])
            print(f"  audio: {audio_url}")

            speaker_names = lesson.get("speaker_names", DEFAULT_SPEAKER_NAMES)
            audio = ListeningAudio(
                title=lesson["title"],
                level=lesson["level"],
                transcript=build_transcript(lesson["turns"], speaker_names),
                audio_url=audio_url,
            )
            db.add(audio)
            db.flush()  # assign audio.id before inserting questions

            for q in lesson["questions"]:
                db.add(
                    ListeningQuestion(
                        audio_id=audio.id,
                        type=q["type"],
                        prompt=q["prompt"],
                        options=q["options"],
                        correct_answer=q["correct_answer"],
                        order=q["order"],
                    )
                )

            db.commit()
            print(f"  Inserted ListeningAudio id={audio.id} with {len(lesson['questions'])} question(s)\n")

        print("Done.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
