"""
Seed script for the Listening feature.

Run:
    cd backend
    python scripts/seed_listening.py
"""
import os
import sys

# Allow importing from the backend root regardless of where the script is run from
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.database import SessionLocal
from app.models.models import ListeningAudio, ListeningQuestion
from app.services.listening_audio import generate_lesson_audio

DEFAULT_SPEAKER_NAMES = {"A": "Woman", "B": "Man"}

LESSONS = [
    {
        "slug": "supermarket-shopping",
        "title": "Shopping at the Supermarket",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Excuse me, can you help me?"),
            ("A", "Of course. What do you need?"),
            ("B", "Where is the milk?"),
            ("A", "The milk is in the dairy section, in aisle five at the back."),
            ("B", "Thank you. And where are the eggs?"),
            ("A", "The eggs are next to the milk, on the bottom shelf."),
            ("B", "Great. I also need rice and bread."),
            ("A", "Rice is in aisle three. Bread is near the entrance, on your left."),
            ("B", "Do you have any fresh fruit?"),
            ("A", "Yes, the fruit and vegetables are at the front of the store."),
            ("B", "Are the bananas on sale today?"),
            ("A", "Yes, they are cheap this week — one dollar a kilo."),
            ("B", "Good. Can I have a basket, please?"),
            ("A", "Of course. The baskets are by the door. The big trolleys are outside."),
            ("B", "A basket is fine, thank you. Okay, I have everything now."),
            ("A", "Great, let's go to the checkout. Did you find everything?"),
            ("B", "Yes, thank you."),
            ("A", "That's twenty-three dollars, please."),
            ("B", "Do you have a plastic bag?"),
            ("A", "Yes, but a bag costs ten cents."),
            ("B", "That's fine. One bag, please."),
            ("A", "Okay, twenty-three dollars and ten cents."),
            ("B", "Here is my card."),
            ("A", "Thank you. Here is your receipt. Please check the expiry date on the milk."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The milk is in aisle ___.", "options": None, "correct_answer": "five|5", "order": 1},
            {"type": "fill_blank", "prompt": "Bananas cost ___ dollar a kilo.", "options": None, "correct_answer": "one|1", "order": 2},
            {"type": "fill_blank", "prompt": "A plastic bag costs ___ cents.", "options": None, "correct_answer": "ten|10", "order": 3},
            {"type": "fill_blank", "prompt": "The total is ___ dollars and ten cents.", "options": None, "correct_answer": "twenty-three|23", "order": 4},
            {"type": "fill_blank", "prompt": "The customer also needs rice and ___.", "options": None, "correct_answer": "bread", "order": 5},
            {"type": "true_false", "prompt": "The eggs are next to the milk.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "The bananas are expensive this week.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The customer takes a big trolley.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The bread is near the entrance.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer pays with cash.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Where is the bread?", "options": ["at the back", "near the entrance", "in aisle five"], "correct_answer": "near the entrance", "order": 11},
            {"type": "mcq", "prompt": "How does the customer pay?", "options": ["cash", "card", "phone"], "correct_answer": "card", "order": 12},
            {"type": "mcq", "prompt": "What should the customer check?", "options": ["the receipt total", "the expiry date on the milk", "the address"], "correct_answer": "the expiry date on the milk", "order": 13},
            {"type": "mcq", "prompt": "Where are the fruit and vegetables?", "options": ["at the front", "in aisle three", "at the back"], "correct_answer": "at the front", "order": 14},
            {"type": "mcq", "prompt": "The eggs are on the ___ shelf.", "options": ["top", "middle", "bottom"], "correct_answer": "bottom", "order": 15},
        ],
    },
    {
        "slug": "asking-directions",
        "title": "Asking for Directions",
        "level": "beginner",
        "speaker_names": {"A": "Local", "B": "Visitor"},
        "turns": [
            ("B", "Excuse me, can you help me?"),
            ("A", "Sure. What are you looking for?"),
            ("B", "How do I get to the train station?"),
            ("A", "It's not far. Go straight down this street."),
            ("B", "Okay, go straight. And then?"),
            ("A", "Then turn left at the traffic lights."),
            ("B", "Turn left at the traffic lights. Okay."),
            ("A", "Yes. Walk past the bank, and the station is on your right."),
            ("B", "It's on my right. Is it far?"),
            ("A", "No, it's about five minutes on foot."),
            ("B", "Great. Is there a pharmacy near here too?"),
            ("A", "Yes. Go back to the traffic lights and turn right."),
            ("B", "Turn right at the traffic lights."),
            ("A", "Yes. The pharmacy is next to the supermarket, on the corner."),
            ("B", "Next to the supermarket, on the corner. Okay."),
            ("A", "It's opposite the post office. You can't miss it."),
            ("B", "Is it open now?"),
            ("A", "Yes, it's open until nine."),
            ("B", "One more thing. Where is the nearest bus stop?"),
            ("A", "The bus stop is across the road, in front of the café."),
            ("B", "Across the road, in front of the café. Which bus goes to the city centre?"),
            ("A", "Take bus number ten. It comes every fifteen minutes."),
            ("B", "Bus number ten. Thank you so much. You are very kind."),
            ("A", "You're welcome. If you get lost, just ask someone again. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "To reach the station, turn left at the ___.", "options": None, "correct_answer": "traffic lights", "order": 1},
            {"type": "fill_blank", "prompt": "The station is about ___ minutes on foot.", "options": None, "correct_answer": "five|5", "order": 2},
            {"type": "fill_blank", "prompt": "The pharmacy is next to the ___.", "options": None, "correct_answer": "supermarket", "order": 3},
            {"type": "fill_blank", "prompt": "Take bus number ___ to the city centre.", "options": None, "correct_answer": "ten|10", "order": 4},
            {"type": "fill_blank", "prompt": "The bus comes every ___ minutes.", "options": None, "correct_answer": "fifteen|15", "order": 5},
            {"type": "true_false", "prompt": "The train station is very far.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The pharmacy is opposite the post office.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The pharmacy is closed now.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The bus stop is across the road.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The pharmacy is next to the café.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "How do you get to the station?", "options": ["go straight then turn left", "turn right immediately", "go back"], "correct_answer": "go straight then turn left", "order": 11},
            {"type": "mcq", "prompt": "The station is on the visitor's:", "options": ["left", "right", "corner"], "correct_answer": "right", "order": 12},
            {"type": "mcq", "prompt": "Where is the pharmacy?", "options": ["on the corner", "inside the station", "next to the bank"], "correct_answer": "on the corner", "order": 13},
            {"type": "mcq", "prompt": "The bus stop is in front of the:", "options": ["bank", "café", "post office"], "correct_answer": "café", "order": 14},
            {"type": "mcq", "prompt": "How often does bus ten come?", "options": ["every 5 minutes", "every 10 minutes", "every 15 minutes"], "correct_answer": "every 15 minutes", "order": 15},
        ],
    },
    {
        "slug": "buying-a-train-ticket",
        "title": "Buying a Train Ticket",
        "level": "beginner",
        "speaker_names": {"A": "Clerk", "B": "Traveller"},
        "turns": [
            ("B", "Hello. I'd like a ticket to Manchester, please."),
            ("A", "Single or return?"),
            ("B", "A return, please. What time is the next train?"),
            ("A", "The next train leaves at ten thirty."),
            ("B", "And how much is a return ticket?"),
            ("A", "It's twenty-five dollars."),
            ("B", "Okay. Which platform is it?"),
            ("A", "Platform four. Go up the stairs and turn right."),
            ("B", "How long is the journey?"),
            ("A", "About two hours. You arrive at half past twelve."),
            ("B", "Is it a direct train?"),
            ("A", "No, you change at Birmingham. Don't worry, you have twenty minutes."),
            ("B", "Do I need to book a seat?"),
            ("A", "No, you don't need to. The train is not busy today."),
            ("B", "Can I pay by card?"),
            ("A", "Yes, card or cash. Both are fine."),
            ("B", "Here is my card."),
            ("A", "Thank you. Here is your ticket. Keep it safe — you need it on the train."),
            ("B", "One more question. Where can I buy a coffee?"),
            ("A", "There is a small shop next to platform two."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good trip!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The traveller wants a ticket to ___.", "options": None, "correct_answer": "Manchester", "order": 1},
            {"type": "fill_blank", "prompt": "The next train leaves at ___ thirty.", "options": None, "correct_answer": "ten|10", "order": 2},
            {"type": "fill_blank", "prompt": "A return ticket costs ___ dollars.", "options": None, "correct_answer": "twenty-five|25", "order": 3},
            {"type": "fill_blank", "prompt": "The train leaves from platform ___.", "options": None, "correct_answer": "four|4", "order": 4},
            {"type": "fill_blank", "prompt": "The traveller changes trains at ___.", "options": None, "correct_answer": "Birmingham", "order": 5},
            {"type": "true_false", "prompt": "The traveller buys a single ticket.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The journey takes about two hours.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "It is a direct train.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The traveller needs to book a seat.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The traveller can pay by card.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What kind of ticket does the traveller buy?", "options": ["single", "return", "weekly"], "correct_answer": "return", "order": 11},
            {"type": "mcq", "prompt": "To find the platform, go up the stairs and turn:", "options": ["left", "right", "back"], "correct_answer": "right", "order": 12},
            {"type": "mcq", "prompt": "What time does the train arrive?", "options": ["ten thirty", "half past twelve", "two o'clock"], "correct_answer": "half past twelve", "order": 13},
            {"type": "mcq", "prompt": "How long does the traveller wait at Birmingham?", "options": ["ten minutes", "twenty minutes", "two hours"], "correct_answer": "twenty minutes", "order": 14},
            {"type": "mcq", "prompt": "Where can the traveller buy a coffee?", "options": ["on the train", "next to platform two", "at platform four"], "correct_answer": "next to platform two", "order": 15},
        ],
    },
    {
        "slug": "buying-clothes",
        "title": "Buying Clothes",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Excuse me, do you have this shirt in a medium?"),
            ("A", "Let me check. Yes, here is a medium. What colour would you like?"),
            ("B", "Do you have it in blue?"),
            ("A", "Yes, we have blue, white, and black."),
            ("B", "I'd like the blue one, please. Can I try it on?"),
            ("A", "Of course. The fitting room is over there, on the left."),
            ("B", "Thank you. Excuse me, it's a little too big. Do you have a small?"),
            ("A", "Yes, here is a small. Try this one."),
            ("B", "This one is perfect. How much is it?"),
            ("A", "It's thirty dollars. But today there is a discount — twenty percent off."),
            ("B", "So how much do I pay?"),
            ("A", "Twenty-four dollars."),
            ("B", "Great. I'll take it. Do you have these shoes in size eight?"),
            ("A", "I'm sorry, size eight is sold out. We have size nine."),
            ("B", "No, thank you. Just the shirt then."),
            ("A", "Okay. Would you like a bag?"),
            ("B", "Yes, please."),
            ("A", "That's twenty-four dollars. How would you like to pay?"),
            ("B", "By card, please. Can I return it if it doesn't fit?"),
            ("A", "Yes, you can return it in fourteen days. Keep the receipt."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a nice day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants the shirt in the colour ___.", "options": None, "correct_answer": "blue", "order": 1},
            {"type": "fill_blank", "prompt": "The shirt costs ___ dollars before the discount.", "options": None, "correct_answer": "thirty|30", "order": 2},
            {"type": "fill_blank", "prompt": "The discount is ___ percent off.", "options": None, "correct_answer": "twenty|20", "order": 3},
            {"type": "fill_blank", "prompt": "After the discount, the customer pays ___ dollars.", "options": None, "correct_answer": "twenty-four|24", "order": 4},
            {"type": "fill_blank", "prompt": "The customer can return the shirt in ___ days.", "options": None, "correct_answer": "fourteen|14", "order": 5},
            {"type": "true_false", "prompt": "The medium shirt is too small.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The fitting room is on the left.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The shoes in size eight are available.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer pays by card.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer must keep the receipt to return the shirt.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Which size fits the customer?", "options": ["medium", "small", "large"], "correct_answer": "small", "order": 11},
            {"type": "mcq", "prompt": "What colours does the shop have?", "options": ["blue white black", "red green", "only blue"], "correct_answer": "blue white black", "order": 12},
            {"type": "mcq", "prompt": "Why is the shirt cheaper today?", "options": ["it is old", "there is a discount", "it is damaged"], "correct_answer": "there is a discount", "order": 13},
            {"type": "mcq", "prompt": "What size shoes does the customer want?", "options": ["eight", "nine", "ten"], "correct_answer": "eight", "order": 14},
            {"type": "mcq", "prompt": "What does the customer buy?", "options": ["shirt and shoes", "only the shirt", "only shoes"], "correct_answer": "only the shirt", "order": 15},
        ],
    },
    {
        "slug": "meeting-a-new-neighbour",
        "title": "Meeting a New Neighbour",
        "level": "beginner",
        "speaker_names": {"A": "Neighbour", "B": "New resident"},
        "turns": [
            ("A", "Hello! Are you the new neighbour?"),
            ("B", "Yes, hello. I moved in yesterday. My name is Ben."),
            ("A", "Nice to meet you, Ben. I'm Susan. I live in number ten."),
            ("B", "Nice to meet you too, Susan."),
            ("A", "Where are you from?"),
            ("B", "I'm from Thailand. I came here last month."),
            ("A", "Welcome! How do you like the area?"),
            ("B", "It's very nice. But I don't know many places yet."),
            ("A", "Don't worry. There is a good supermarket near here. It opens at eight."),
            ("B", "That's good to know. Is there a park nearby?"),
            ("A", "Yes, there is a park at the end of the street. It's very quiet."),
            ("B", "Great. I have a small dog. Is that okay here?"),
            ("A", "Yes, many people have pets. Dogs are welcome."),
            ("B", "Good. What day is rubbish collection?"),
            ("A", "The rubbish truck comes on Wednesday morning. Put your bins outside on Tuesday night."),
            ("B", "Wednesday morning. Thank you."),
            ("A", "If you need anything, just knock on my door."),
            ("B", "Thank you, Susan. You are very kind."),
            ("A", "No problem. Welcome to the street, Ben!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The new resident's name is ___.", "options": None, "correct_answer": "Ben", "order": 1},
            {"type": "fill_blank", "prompt": "The neighbour's name is ___.", "options": None, "correct_answer": "Susan", "order": 2},
            {"type": "fill_blank", "prompt": "The new resident is from ___.", "options": None, "correct_answer": "Thailand", "order": 3},
            {"type": "fill_blank", "prompt": "The supermarket opens at ___.", "options": None, "correct_answer": "eight|8", "order": 4},
            {"type": "fill_blank", "prompt": "Rubbish collection is on ___ morning.", "options": None, "correct_answer": "Wednesday", "order": 5},
            {"type": "true_false", "prompt": "Ben moved in last week.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "There is a park at the end of the street.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Pets are not allowed on the street.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "Susan lives in number ten.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Ben has a cat.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "When did Ben move in?", "options": ["yesterday", "last week", "last year"], "correct_answer": "yesterday", "order": 11},
            {"type": "mcq", "prompt": "Where is the park?", "options": ["at the end of the street", "next to the supermarket", "far away"], "correct_answer": "at the end of the street", "order": 12},
            {"type": "mcq", "prompt": "What pet does Ben have?", "options": ["a cat", "a small dog", "a bird"], "correct_answer": "a small dog", "order": 13},
            {"type": "mcq", "prompt": "When should Ben put the bins outside?", "options": ["Wednesday morning", "Tuesday night", "Monday"], "correct_answer": "Tuesday night", "order": 14},
            {"type": "mcq", "prompt": "What does Susan say if Ben needs help?", "options": ["call the office", "knock on her door", "send a letter"], "correct_answer": "knock on her door", "order": 15},
        ],
    },
    {
        "slug": "at-the-post-office",
        "title": "At the Post Office",
        "level": "beginner",
        "speaker_names": {"A": "Clerk", "B": "Customer"},
        "turns": [
            ("B", "Hello. I want to send this letter to Canada."),
            ("A", "Okay. Put it on the scale, please. It's twenty grams."),
            ("B", "How much is it?"),
            ("A", "To Canada, it's two dollars."),
            ("B", "Okay. I also want to send this box to my family."),
            ("A", "Where to?"),
            ("B", "To Thailand."),
            ("A", "Put the box on the scale. It's three kilos. That's fifteen dollars."),
            ("B", "How long does it take?"),
            ("A", "The letter takes one week. The box takes about two weeks."),
            ("B", "Is there a faster way for the box?"),
            ("A", "Yes, express post takes five days, but it costs twenty-five dollars."),
            ("B", "No, two weeks is fine. The normal way, please."),
            ("A", "Okay. Do you want to track the box?"),
            ("B", "Yes, please. What is tracking?"),
            ("A", "You get a number. You can check where the box is online."),
            ("B", "Great. I'll take it."),
            ("A", "Okay. Two dollars for the letter, fifteen for the box. Seventeen dollars in total."),
            ("B", "Here is twenty dollars."),
            ("A", "Thank you. Here is your change — three dollars — and your tracking number. Keep it safe."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer sends a letter to ___.", "options": None, "correct_answer": "Canada", "order": 1},
            {"type": "fill_blank", "prompt": "The letter costs ___ dollars.", "options": None, "correct_answer": "two|2", "order": 2},
            {"type": "fill_blank", "prompt": "The box weighs ___ kilos.", "options": None, "correct_answer": "three|3", "order": 3},
            {"type": "fill_blank", "prompt": "The box costs ___ dollars.", "options": None, "correct_answer": "fifteen|15", "order": 4},
            {"type": "fill_blank", "prompt": "The total is ___ dollars.", "options": None, "correct_answer": "seventeen|17", "order": 5},
            {"type": "true_false", "prompt": "The letter goes to Thailand.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The box takes about two weeks.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Express post is cheaper than normal post.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer wants to track the box.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer pays with a twenty-dollar note.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Where does the box go?", "options": ["Canada", "Thailand", "Japan"], "correct_answer": "Thailand", "order": 11},
            {"type": "mcq", "prompt": "How long does the letter take?", "options": ["one week", "two weeks", "five days"], "correct_answer": "one week", "order": 12},
            {"type": "mcq", "prompt": "How much is express post for the box?", "options": ["fifteen dollars", "twenty dollars", "twenty-five dollars"], "correct_answer": "twenty-five dollars", "order": 13},
            {"type": "mcq", "prompt": "What does the customer get to track the box?", "options": ["a receipt", "a number", "an email"], "correct_answer": "a number", "order": 14},
            {"type": "mcq", "prompt": "How much change does the customer get?", "options": ["two dollars", "three dollars", "five dollars"], "correct_answer": "three dollars", "order": 15},
        ],
    },
    {
        "slug": "making-weekend-plans",
        "title": "Making Weekend Plans",
        "level": "beginner",
        "speaker_names": {"A": "Mia", "B": "Tom"},
        "turns": [
            ("A", "Hi Tom! Are you free this weekend?"),
            ("B", "Hi Mia! Yes, I think so. Why?"),
            ("A", "Do you want to go to the cinema?"),
            ("B", "Sure! What film do you want to see?"),
            ("A", "There is a new action film. It looks really good."),
            ("B", "Nice. What day is good for you?"),
            ("A", "Saturday or Sunday. I don't mind."),
            ("B", "Let's go on Saturday. I'm busy on Sunday."),
            ("A", "Okay, Saturday. What time?"),
            ("B", "How about the afternoon? Maybe two o'clock?"),
            ("A", "Two is perfect. But the film is quite long. It finishes at four thirty."),
            ("B", "That's fine. Actually, do you want to have lunch first?"),
            ("A", "Good idea! Let's meet at twelve for lunch, then the film."),
            ("B", "Great. Where do you want to eat?"),
            ("A", "There is a nice pizza place near the cinema."),
            ("B", "I love pizza! Let's go there."),
            ("A", "Perfect. By the way, can you bring your sister?"),
            ("B", "Sure, she likes films too. She can come."),
            ("A", "Wonderful. See you on Saturday at twelve!"),
            ("B", "See you then. Have a good week!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "They want to go to the ___.", "options": None, "correct_answer": "cinema", "order": 1},
            {"type": "fill_blank", "prompt": "They decide to go on ___.", "options": None, "correct_answer": "Saturday", "order": 2},
            {"type": "fill_blank", "prompt": "They will meet at ___ o'clock for lunch.", "options": None, "correct_answer": "twelve|12", "order": 3},
            {"type": "fill_blank", "prompt": "The film finishes at ___ thirty.", "options": None, "correct_answer": "four|4", "order": 4},
            {"type": "fill_blank", "prompt": "They will eat at a ___ place.", "options": None, "correct_answer": "pizza", "order": 5},
            {"type": "true_false", "prompt": "Tom is busy on Sunday.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "They will see a comedy film.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "They will have lunch after the film.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The pizza place is near the cinema.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Tom's sister will come too.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What do they want to watch?", "options": ["an action film", "a comedy", "a cartoon"], "correct_answer": "an action film", "order": 11},
            {"type": "mcq", "prompt": "Why not Sunday?", "options": ["the cinema is closed", "Tom is busy", "Mia is busy"], "correct_answer": "Tom is busy", "order": 12},
            {"type": "mcq", "prompt": "What time is the film?", "options": ["twelve", "two", "four thirty"], "correct_answer": "two", "order": 13},
            {"type": "mcq", "prompt": "What do they do before the film?", "options": ["shopping", "have lunch", "go home"], "correct_answer": "have lunch", "order": 14},
            {"type": "mcq", "prompt": "Who else will come?", "options": ["Tom's brother", "Tom's sister", "Mia's friend"], "correct_answer": "Tom's sister", "order": 15},
        ],
    },
    {
        "slug": "calling-your-parents",
        "title": "Calling Your Parents",
        "level": "beginner",
        "speaker_names": {"A": "Mum", "B": "Child"},
        "turns": [
            ("B", "Hi Mum! How are you?"),
            ("A", "Hello! I'm fine, thank you. How are you? Are you eating well?"),
            ("B", "Yes, Mum. Don't worry. I cook every day."),
            ("A", "Good. And how is your new job?"),
            ("B", "It's good. My boss is very kind, and I like my colleagues."),
            ("A", "I'm so happy. Is it cold there?"),
            ("B", "Yes, it's a little cold now. But I have a warm coat."),
            ("A", "Good. Remember to wear a scarf. How is your friend, Lily?"),
            ("B", "She is fine. We meet every weekend."),
            ("A", "That's nice. You are not alone, then."),
            ("B", "No, I'm okay. How is Dad?"),
            ("A", "He is fine. He is in the garden now. He misses you."),
            ("B", "I miss him too. Actually, I have good news, Mum."),
            ("A", "Oh? What is it?"),
            ("B", "I passed my English test!"),
            ("A", "That's wonderful! I'm so proud of you."),
            ("B", "Thank you, Mum. By the way, can we video call on Sunday?"),
            ("A", "Of course! Sunday evening is good for me."),
            ("B", "Perfect. I will call at seven, your time."),
            ("A", "Okay. Take care of yourself. We love you."),
            ("B", "I love you too. Talk to you on Sunday. Bye!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The child cooks ___ day.", "options": None, "correct_answer": "every", "order": 1},
            {"type": "fill_blank", "prompt": "The child's new ___ is very kind.", "options": None, "correct_answer": "boss", "order": 2},
            {"type": "fill_blank", "prompt": "The weather there is a little ___.", "options": None, "correct_answer": "cold", "order": 3},
            {"type": "fill_blank", "prompt": "The child's friend's name is ___.", "options": None, "correct_answer": "Lily", "order": 4},
            {"type": "fill_blank", "prompt": "They will video call on ___.", "options": None, "correct_answer": "Sunday", "order": 5},
            {"type": "true_false", "prompt": "The child does not cook.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The child likes the colleagues.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Dad is in the garden.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The child failed the English test.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The video call is on Sunday evening.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How is the new job?", "options": ["bad", "good", "boring"], "correct_answer": "good", "order": 11},
            {"type": "mcq", "prompt": "What does Mum tell the child to wear?", "options": ["a hat", "a scarf", "gloves"], "correct_answer": "a scarf", "order": 12},
            {"type": "mcq", "prompt": "What good news does the child share?", "options": ["a new job", "passed the English test", "a new house"], "correct_answer": "passed the English test", "order": 13},
            {"type": "mcq", "prompt": "Where is Dad?", "options": ["at work", "in the garden", "sleeping"], "correct_answer": "in the garden", "order": 14},
            {"type": "mcq", "prompt": "What time will the child call on Sunday?", "options": ["seven", "eight", "nine"], "correct_answer": "seven", "order": 15},
        ],
    },
    {
        "slug": "cooking-dinner-together",
        "title": "Cooking Dinner Together",
        "level": "beginner",
        "speaker_names": {"A": "Partner A", "B": "Partner B"},
        "turns": [
            ("A", "I'm hungry. What do you want to eat tonight?"),
            ("B", "I don't know. What do we have in the fridge?"),
            ("A", "Let me see. We have eggs, tomatoes, and some cheese."),
            ("B", "We can make an omelette. Do we have any onions?"),
            ("A", "Yes, there are two onions here. And some bread."),
            ("B", "Perfect. Let's make a cheese omelette with bread."),
            ("A", "Good idea. But we don't have any milk."),
            ("B", "That's okay. We don't need milk for an omelette."),
            ("A", "Okay. Can you cut the tomatoes and onions?"),
            ("B", "Sure. And can you break the eggs?"),
            ("A", "Yes. How many eggs? Four?"),
            ("B", "Four is good. Two for you and two for me."),
            ("A", "Okay. Where is the salt?"),
            ("B", "It's next to the stove, on the right."),
            ("A", "Got it. Actually, do you want some tea after dinner?"),
            ("B", "Yes please. By the way, the rice is finished. We need to buy more tomorrow."),
            ("A", "Okay, I'll write it on the list. Anything else?"),
            ("B", "Yes, milk and onions. We are nearly out."),
            ("A", "Good. The omelette smells nice already!"),
            ("B", "I'm so hungry. Let's eat!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "They decide to make a cheese ___.", "options": None, "correct_answer": "omelette", "order": 1},
            {"type": "fill_blank", "prompt": "There are ___ onions in the kitchen.", "options": None, "correct_answer": "two|2", "order": 2},
            {"type": "fill_blank", "prompt": "They will use ___ eggs.", "options": None, "correct_answer": "four|4", "order": 3},
            {"type": "fill_blank", "prompt": "The salt is next to the ___.", "options": None, "correct_answer": "stove", "order": 4},
            {"type": "fill_blank", "prompt": "They need to buy more ___ tomorrow.", "options": None, "correct_answer": "rice", "order": 5},
            {"type": "true_false", "prompt": "They have milk in the fridge.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "They need milk for the omelette.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "They will have tea after dinner.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "There is bread in the kitchen.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "They will buy milk and onions tomorrow.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What do they decide to cook?", "options": ["rice", "a cheese omelette", "soup"], "correct_answer": "a cheese omelette", "order": 11},
            {"type": "mcq", "prompt": "How many eggs do they use?", "options": ["two", "three", "four"], "correct_answer": "four", "order": 12},
            {"type": "mcq", "prompt": "Where is the salt?", "options": ["in the fridge", "next to the stove", "on the table"], "correct_answer": "next to the stove", "order": 13},
            {"type": "mcq", "prompt": "What do they want after dinner?", "options": ["coffee", "tea", "juice"], "correct_answer": "tea", "order": 14},
            {"type": "mcq", "prompt": "What is finished and needs buying?", "options": ["bread", "rice", "cheese"], "correct_answer": "rice", "order": 15},
        ],
    },
    {
        "slug": "ordering-at-a-restaurant",
        "title": "Ordering at a Restaurant",
        "level": "beginner",
        "speaker_names": {"A": "Waiter", "B": "Customer"},
        "turns": [
            ("A", "Good evening. A table for how many?"),
            ("B", "For two, please."),
            ("A", "This way, please. Here is the menu."),
            ("B", "Thank you. Can we have some water first?"),
            ("A", "Of course. Still or sparkling?"),
            ("B", "Still, please. Okay, we are ready to order."),
            ("A", "Great. What would you like?"),
            ("B", "I'd like the chicken soup to start, and then the fish."),
            ("A", "Good choice. And for your friend?"),
            ("B", "She wants a salad and the pasta."),
            ("A", "Would you like anything to drink?"),
            ("B", "Two orange juices, please. Actually, make one apple juice."),
            ("A", "One orange and one apple. No problem."),
            ("B", "Is the fish spicy?"),
            ("A", "No, it's not spicy. But the pasta is a little spicy."),
            ("B", "That's fine. She likes spicy food."),
            ("A", "Perfect. Your food will be ready in about fifteen minutes."),
            ("B", "Thank you. By the way, do you have any vegetarian dishes?"),
            ("A", "Yes, the salad and the vegetable soup are vegetarian."),
            ("B", "Good to know. Can we have the bill together at the end?"),
            ("A", "Of course. I'll bring everything now."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Enjoy your meal!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants a table for ___.", "options": None, "correct_answer": "two|2", "order": 1},
            {"type": "fill_blank", "prompt": "To start, the customer orders chicken ___.", "options": None, "correct_answer": "soup", "order": 2},
            {"type": "fill_blank", "prompt": "The food will be ready in about ___ minutes.", "options": None, "correct_answer": "fifteen|15", "order": 3},
            {"type": "fill_blank", "prompt": "The customer changes one drink to ___ juice.", "options": None, "correct_answer": "apple", "order": 4},
            {"type": "fill_blank", "prompt": "The friend orders a salad and the ___.", "options": None, "correct_answer": "pasta", "order": 5},
            {"type": "true_false", "prompt": "The customer orders sparkling water.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The fish is spicy.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The pasta is a little spicy.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The salad is vegetarian.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The customer wants the bill at the end.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How many people are at the table?", "options": ["one", "two", "three"], "correct_answer": "two", "order": 11},
            {"type": "mcq", "prompt": "What does the customer order to eat?", "options": ["soup and fish", "salad and pasta", "only fish"], "correct_answer": "soup and fish", "order": 12},
            {"type": "mcq", "prompt": "What does the friend like?", "options": ["sweet food", "spicy food", "cold food"], "correct_answer": "spicy food", "order": 13},
            {"type": "mcq", "prompt": "Which dishes are vegetarian?", "options": ["salad and vegetable soup", "fish and pasta", "chicken soup"], "correct_answer": "salad and vegetable soup", "order": 14},
            {"type": "mcq", "prompt": "When does the customer want the bill?", "options": ["before the food", "together at the end", "with each dish"], "correct_answer": "together at the end", "order": 15},
        ],
    },
    {
        "slug": "booking-a-table-by-phone",
        "title": "Booking a Table by Phone",
        "level": "beginner",
        "speaker_names": {"A": "Staff", "B": "Caller"},
        "turns": [
            ("A", "Hello, Garden Restaurant. How can I help you?"),
            ("B", "Hello. I'd like to book a table, please."),
            ("A", "Of course. For which day?"),
            ("B", "For this Friday evening."),
            ("A", "And what time?"),
            ("B", "At seven o'clock. Is that okay?"),
            ("A", "Let me check. Yes, seven o'clock is fine. For how many people?"),
            ("B", "For four people."),
            ("A", "A table for four at seven on Friday. Can I have your name?"),
            ("B", "Yes, my name is David Lee."),
            ("A", "Thank you, Mr Lee. Do you want a table inside or outside?"),
            ("B", "Outside, please. But if it rains, inside is fine."),
            ("A", "No problem. Actually, the weather is nice this week."),
            ("B", "Good. What time do you close?"),
            ("A", "We close at eleven. The kitchen closes at ten."),
            ("B", "Okay. Are you open on Mondays?"),
            ("A", "No, we are closed on Mondays. We open from Tuesday to Sunday."),
            ("B", "Good to know. By the way, do you have parking?"),
            ("A", "Yes, there is free parking behind the restaurant."),
            ("B", "Perfect. Thank you very much."),
            ("A", "You're welcome, Mr Lee. See you on Friday!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The caller wants to book a table for ___ people.", "options": None, "correct_answer": "four|4", "order": 1},
            {"type": "fill_blank", "prompt": "The booking is for ___ evening.", "options": None, "correct_answer": "Friday", "order": 2},
            {"type": "fill_blank", "prompt": "The table is booked at ___ o'clock.", "options": None, "correct_answer": "seven|7", "order": 3},
            {"type": "fill_blank", "prompt": "The caller's name is David ___.", "options": None, "correct_answer": "Lee", "order": 4},
            {"type": "fill_blank", "prompt": "The restaurant closes at ___.", "options": None, "correct_answer": "eleven|11", "order": 5},
            {"type": "true_false", "prompt": "The caller wants a table inside.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The kitchen closes at ten.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The restaurant is open on Mondays.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "There is free parking behind the restaurant.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The restaurant opens from Tuesday to Sunday.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How many people is the table for?", "options": ["two", "four", "six"], "correct_answer": "four", "order": 11},
            {"type": "mcq", "prompt": "Where does the caller want to sit?", "options": ["inside", "outside", "at the bar"], "correct_answer": "outside", "order": 12},
            {"type": "mcq", "prompt": "What time does the kitchen close?", "options": ["ten", "eleven", "seven"], "correct_answer": "ten", "order": 13},
            {"type": "mcq", "prompt": "When is the restaurant closed?", "options": ["Sundays", "Mondays", "Fridays"], "correct_answer": "Mondays", "order": 14},
            {"type": "mcq", "prompt": "Where is the parking?", "options": ["in front", "behind the restaurant", "across the road"], "correct_answer": "behind the restaurant", "order": 15},
        ],
    },
    {
        "slug": "buying-a-sim-card",
        "title": "Buying a SIM Card",
        "level": "beginner",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Hello. I need a SIM card for my phone."),
            ("A", "Sure. Are you a visitor or do you live here?"),
            ("B", "I live here now. I just moved last month."),
            ("A", "Okay. Do you want a monthly plan or pay as you go?"),
            ("B", "What is the difference?"),
            ("A", "With a monthly plan, you pay every month. Pay as you go, you only pay when you use it."),
            ("B", "I think a monthly plan is better. How much is it?"),
            ("A", "This plan is twenty dollars a month. You get lots of data, calls, and texts."),
            ("B", "That sounds good. Do I need my passport?"),
            ("A", "Yes, please. I need to see your ID."),
            ("B", "Here is my passport."),
            ("A", "Thank you. Actually, do you have an address here?"),
            ("B", "Yes, here is a letter with my address."),
            ("A", "Perfect. The SIM card is free with this plan."),
            ("B", "Great. How long does it take to work?"),
            ("A", "It works in about one hour. But sometimes it is faster."),
            ("B", "Okay. Can I keep my old phone number?"),
            ("A", "Yes, but you need to bring a letter from your old company."),
            ("B", "I don't have it now. I'll get a new number then."),
            ("A", "No problem. Here is your new SIM card and your number."),
            ("B", "Thank you very much."),
            ("A", "You're welcome. Enjoy your new plan!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer needs a SIM card for their ___.", "options": None, "correct_answer": "phone", "order": 1},
            {"type": "fill_blank", "prompt": "The monthly plan costs ___ dollars a month.", "options": None, "correct_answer": "twenty|20", "order": 2},
            {"type": "fill_blank", "prompt": "The assistant needs to see the customer's ___.", "options": None, "correct_answer": "passport", "order": 3},
            {"type": "fill_blank", "prompt": "The SIM card works in about one ___.", "options": None, "correct_answer": "hour", "order": 4},
            {"type": "fill_blank", "prompt": "To keep the old number, the customer needs a letter from the old ___.", "options": None, "correct_answer": "company", "order": 5},
            {"type": "true_false", "prompt": "The customer is just a visitor.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The SIM card is free with the plan.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The customer chooses pay as you go.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer keeps the old phone number.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The plan includes data, calls, and texts.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Which plan does the customer choose?", "options": ["monthly plan", "pay as you go", "no plan"], "correct_answer": "monthly plan", "order": 11},
            {"type": "mcq", "prompt": "What does the customer show as ID?", "options": ["a driving licence", "a passport", "a bank card"], "correct_answer": "a passport", "order": 12},
            {"type": "mcq", "prompt": "How long does the SIM take to work?", "options": ["one hour", "one day", "one week"], "correct_answer": "one hour", "order": 13},
            {"type": "mcq", "prompt": "What does the customer need to keep the old number?", "options": ["a passport", "a letter from the old company", "money"], "correct_answer": "a letter from the old company", "order": 14},
            {"type": "mcq", "prompt": "What does the customer decide about the number?", "options": ["keep the old one", "get a new one", "use two numbers"], "correct_answer": "get a new one", "order": 15},
        ],
    },
    {
        "slug": "a-doctors-visit",
        "title": "A Doctor's Visit",
        "level": "elementary",
        "speaker_names": {"A": "Doctor", "B": "Patient"},
        "turns": [
            ("A", "Good morning. Please sit down. What's the problem today?"),
            ("B", "Good morning, doctor. I don't feel well. I have a bad stomach ache."),
            ("A", "I'm sorry to hear that. When did it start?"),
            ("B", "It started two days ago, after I ate at a restaurant."),
            ("A", "I see. Do you have any other symptoms?"),
            ("B", "Yes. I feel sick, and I was sick yesterday morning."),
            ("A", "Are you eating normally?"),
            ("B", "No, I can't eat much. I'm only drinking water and a little soup."),
            ("A", "That's okay for now. Let me check your temperature. It's a little high — thirty-eight degrees."),
            ("B", "Is it serious, doctor?"),
            ("A", "No, don't worry. I think it's food poisoning. It's quite common."),
            ("B", "What should I do?"),
            ("A", "First, are you allergic to any medicine?"),
            ("B", "No, I'm not allergic to anything."),
            ("A", "Good. You should rest and drink a lot of water. Don't eat heavy food for two days."),
            ("B", "Okay. Should I take any medicine?"),
            ("A", "Yes, I'll give you some tablets for your stomach. Take one after every meal, for three days."),
            ("B", "After every meal, for three days. Actually, can I go to work tomorrow?"),
            ("A", "No, you should stay home and rest. Go back when you feel better. If you feel worse, come back immediately."),
            ("B", "I understand. By the way, do I need to pay now?"),
            ("A", "Pay at the front desk. The nurse will give you the prescription too."),
            ("B", "Thank you very much, doctor."),
            ("A", "You're welcome. Take care and get well soon!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The patient has a bad stomach ___.", "options": None, "correct_answer": "ache", "order": 1},
            {"type": "fill_blank", "prompt": "The problem started ___ days ago.", "options": None, "correct_answer": "two|2", "order": 2},
            {"type": "fill_blank", "prompt": "The patient's temperature is ___ degrees.", "options": None, "correct_answer": "thirty-eight|38", "order": 3},
            {"type": "fill_blank", "prompt": "The patient should take one tablet after every ___.", "options": None, "correct_answer": "meal", "order": 4},
            {"type": "fill_blank", "prompt": "The patient should take the tablets for ___ days.", "options": None, "correct_answer": "three|3", "order": 5},
            {"type": "true_false", "prompt": "The stomach ache started after eating at a restaurant.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "The patient can eat a lot of food now.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The doctor thinks it is food poisoning.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The patient is allergic to some medicine.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The patient can go to work tomorrow.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "When did the problem start?", "options": ["today", "two days ago", "last week"], "correct_answer": "two days ago", "order": 11},
            {"type": "mcq", "prompt": "What does the doctor say it is?", "options": ["a cold", "food poisoning", "flu"], "correct_answer": "food poisoning", "order": 12},
            {"type": "mcq", "prompt": "What should the patient drink?", "options": ["coffee", "a lot of water", "milk"], "correct_answer": "a lot of water", "order": 13},
            {"type": "mcq", "prompt": "When should the patient come back?", "options": ["tomorrow", "if he feels worse", "next month"], "correct_answer": "if he feels worse", "order": 14},
            {"type": "mcq", "prompt": "Where does the patient pay?", "options": ["to the doctor", "at the front desk", "online"], "correct_answer": "at the front desk", "order": 15},
        ],
    },
    {
        "slug": "opening-a-bank-account",
        "title": "Opening a Bank Account",
        "level": "elementary",
        "speaker_names": {"A": "Clerk", "B": "Customer"},
        "turns": [
            ("B", "Hello. I'd like to open a bank account, please."),
            ("A", "Of course. Are you opening a personal account?"),
            ("B", "Yes, a personal account. I just moved here and I need one for my salary."),
            ("A", "No problem. Do you have your passport and a proof of address?"),
            ("B", "Yes, here is my passport. And I have a letter from my landlord with my address."),
            ("A", "Perfect, that's fine. What kind of account would you like? We have a basic account and a savings account."),
            ("B", "What's the difference?"),
            ("A", "With the basic account, you can pay bills and use a card every day. The savings account gives you a little interest, but you can't use it for daily shopping."),
            ("B", "I think the basic account is better for me. Maybe I'll open a savings account later."),
            ("A", "Good choice. The basic account is free. There are no monthly fees."),
            ("B", "That's great. Do I get a card?"),
            ("A", "Yes, you get a debit card. It will arrive by post in about one week."),
            ("B", "Okay. Can I use online banking too?"),
            ("A", "Of course. You can check your money and pay bills on your phone."),
            ("B", "Perfect. Actually, how much money do I need to open the account?"),
            ("A", "You only need ten dollars to start."),
            ("B", "Okay, here is twenty dollars."),
            ("A", "Thank you. I'll put twenty dollars in your new account. Please sign here."),
            ("B", "Sure. By the way, where is the nearest cash machine?"),
            ("A", "There's one outside the bank, next to the door."),
            ("B", "Great. Thank you very much for your help."),
            ("A", "You're welcome. Welcome to our bank, and have a good day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants to open a ___ account.", "options": None, "correct_answer": "personal", "order": 1},
            {"type": "fill_blank", "prompt": "The customer shows a passport and a proof of ___.", "options": None, "correct_answer": "address", "order": 2},
            {"type": "fill_blank", "prompt": "The basic account has no monthly ___.", "options": None, "correct_answer": "fees", "order": 3},
            {"type": "fill_blank", "prompt": "The card will arrive in about one ___.", "options": None, "correct_answer": "week", "order": 4},
            {"type": "fill_blank", "prompt": "The customer needs only ___ dollars to open the account.", "options": None, "correct_answer": "ten|10", "order": 5},
            {"type": "true_false", "prompt": "The customer just moved here.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "The savings account is good for daily shopping.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The basic account is free.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The customer can use online banking.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The cash machine is far from the bank.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Why does the customer need the account?", "options": ["for shopping", "for his salary", "for travel"], "correct_answer": "for his salary", "order": 11},
            {"type": "mcq", "prompt": "Which account does the customer choose?", "options": ["basic", "savings", "business"], "correct_answer": "basic", "order": 12},
            {"type": "mcq", "prompt": "How does the card arrive?", "options": ["by email", "by post", "at the bank"], "correct_answer": "by post", "order": 13},
            {"type": "mcq", "prompt": "How much does the customer give the clerk?", "options": ["ten dollars", "twenty dollars", "fifty dollars"], "correct_answer": "twenty dollars", "order": 14},
            {"type": "mcq", "prompt": "Where is the cash machine?", "options": ["inside the bank", "outside next to the door", "across the road"], "correct_answer": "outside next to the door", "order": 15},
        ],
    },
    {
        "slug": "catching-up-with-an-old-friend",
        "title": "Catching Up with an Old Friend",
        "level": "elementary",
        "speaker_names": {"A": "Sarah", "B": "Mark"},
        "turns": [
            ("B", "Sarah! Is that you? Long time no see!"),
            ("A", "Mark! Wow, hello! How are you?"),
            ("B", "I'm great, thank you! What are you doing here?"),
            ("A", "I'm shopping for a birthday present for my sister. What about you?"),
            ("B", "I'm just buying some coffee. So, how is everything? Where do you work now?"),
            ("A", "I changed my job last year. Now I work at a hospital. I'm a nurse."),
            ("B", "A nurse! That's wonderful. Do you like it?"),
            ("A", "Yes, I love it. It's busy, but the people are very kind. And you? Are you still a teacher?"),
            ("B", "Yes, I'm still teaching. But I moved to a new school. It's bigger and closer to my house."),
            ("A", "That's good news. How is your family?"),
            ("B", "Everyone is fine. My son started university this year."),
            ("A", "Really? Time goes so fast! He was so small before."),
            ("B", "I know! Actually, we should meet for dinner soon. Are you free next weekend?"),
            ("A", "Next weekend is a little busy. But I'm free the weekend after. How about Saturday?"),
            ("B", "Saturday is perfect. Let's go to that Italian restaurant near the park."),
            ("A", "I love that place! Okay, let's meet at seven."),
            ("B", "Great. By the way, do you still have my phone number?"),
            ("A", "I think so, but give it to me again to be sure."),
            ("B", "Okay, I'll send you a message now."),
            ("A", "Perfect. It was so nice to see you, Mark!"),
            ("B", "You too, Sarah. See you next Saturday!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "Mark is buying some ___.", "options": None, "correct_answer": "coffee", "order": 1},
            {"type": "fill_blank", "prompt": "Sarah changed her job ___ year.", "options": None, "correct_answer": "last", "order": 2},
            {"type": "fill_blank", "prompt": "Sarah works at a ___ now.", "options": None, "correct_answer": "hospital", "order": 3},
            {"type": "fill_blank", "prompt": "Mark's son started ___ this year.", "options": None, "correct_answer": "university", "order": 4},
            {"type": "fill_blank", "prompt": "They will meet at the ___ restaurant.", "options": None, "correct_answer": "Italian", "order": 5},
            {"type": "true_false", "prompt": "Sarah is a teacher now.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "Mark moved to a new school.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Mark's new school is smaller than the old one.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "They will meet next weekend.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "They decide to meet at seven.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "What is Sarah shopping for?", "options": ["a birthday present", "coffee", "clothes"], "correct_answer": "a birthday present", "order": 11},
            {"type": "mcq", "prompt": "What is Sarah's new job?", "options": ["teacher", "nurse", "doctor"], "correct_answer": "nurse", "order": 12},
            {"type": "mcq", "prompt": "Why is Mark's new school better for him?", "options": ["it pays more", "it's bigger and closer to home", "it's quieter"], "correct_answer": "it's bigger and closer to home", "order": 13},
            {"type": "mcq", "prompt": "When will they meet?", "options": ["next weekend", "the weekend after on Saturday", "tonight"], "correct_answer": "the weekend after on Saturday", "order": 14},
            {"type": "mcq", "prompt": "How will Mark give his number?", "options": ["write it down", "send a message", "say it"], "correct_answer": "send a message", "order": 15},
        ],
    },
    {
        "slug": "first-day-at-a-new-job",
        "title": "First Day at a New Job",
        "level": "elementary",
        "speaker_names": {"A": "Manager", "B": "New employee"},
        "turns": [
            ("A", "Good morning! You must be Daniel, our new team member."),
            ("B", "Yes, good morning. Nice to meet you."),
            ("A", "Nice to meet you too. I'm Karen, your manager. Welcome to the company!"),
            ("B", "Thank you. I'm a little nervous, but I'm excited to start."),
            ("A", "Don't worry, everyone is very friendly here. Let me show you around. This is your desk."),
            ("B", "Great, it's a nice desk. Where can I put my bag?"),
            ("A", "There's a locker for you over there. Here is the key."),
            ("B", "Thank you. What time does work start every day?"),
            ("A", "We start at nine and finish at five. You can take one hour for lunch."),
            ("B", "Okay. Where do people have lunch?"),
            ("A", "There's a kitchen on the second floor. You can also go to the cafés outside."),
            ("B", "Good to know. What should I do first today?"),
            ("A", "First, you must finish some paperwork for the office. Then I'll introduce you to the team."),
            ("B", "Sure. Actually, do I need a password for the computer?"),
            ("A", "Yes, the IT person will give you one this morning. He's coming at ten."),
            ("B", "Perfect. What is my main job?"),
            ("A", "You're going to work with the customer service team. You'll answer emails and help customers."),
            ("B", "That sounds good. I like helping people."),
            ("A", "Wonderful. If you have any questions, just ask me or your colleagues. Don't be shy."),
            ("B", "Thank you, Karen. By the way, where is the bathroom?"),
            ("A", "It's at the end of the corridor, on the right."),
            ("B", "Thank you. I'm ready to start!"),
            ("A", "Great attitude! Let's meet the team now."),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The new employee's name is ___.", "options": None, "correct_answer": "Daniel", "order": 1},
            {"type": "fill_blank", "prompt": "The manager's name is ___.", "options": None, "correct_answer": "Karen", "order": 2},
            {"type": "fill_blank", "prompt": "Work starts at ___ every day.", "options": None, "correct_answer": "nine|9", "order": 3},
            {"type": "fill_blank", "prompt": "Lunch is one ___ long.", "options": None, "correct_answer": "hour", "order": 4},
            {"type": "fill_blank", "prompt": "The IT person is coming at ___.", "options": None, "correct_answer": "ten|10", "order": 5},
            {"type": "true_false", "prompt": "Daniel feels a little nervous.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "There is a locker for Daniel.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Work finishes at six.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "Daniel will work with the customer service team.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "The kitchen is on the first floor.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Who is Karen?", "options": ["a colleague", "the manager", "the IT person"], "correct_answer": "the manager", "order": 11},
            {"type": "mcq", "prompt": "What must Daniel do first?", "options": ["meet the team", "finish some paperwork", "answer emails"], "correct_answer": "finish some paperwork", "order": 12},
            {"type": "mcq", "prompt": "What is Daniel's main job?", "options": ["cleaning", "customer service", "cooking"], "correct_answer": "customer service", "order": 13},
            {"type": "mcq", "prompt": "Where can Daniel have lunch?", "options": ["only at his desk", "the kitchen or cafés outside", "at home"], "correct_answer": "the kitchen or cafés outside", "order": 14},
            {"type": "mcq", "prompt": "Where is the bathroom?", "options": ["at the end of the corridor", "on the second floor", "outside"], "correct_answer": "at the end of the corridor", "order": 15},
        ],
    },
    {
        "slug": "an-apartment-viewing",
        "title": "An Apartment Viewing",
        "level": "elementary",
        "speaker_names": {"A": "Agent", "B": "Viewer"},
        "turns": [
            ("A", "Hello! You must be here to see the apartment."),
            ("B", "Yes, hello. We talked on the phone yesterday."),
            ("A", "That's right. Please come in. This is the living room."),
            ("B", "It's bigger than I thought. And it's very bright."),
            ("A", "Yes, the windows face south, so it gets a lot of sun."),
            ("B", "Nice. How many bedrooms are there?"),
            ("A", "There are two bedrooms. This one is the big one, and the second one is smaller."),
            ("B", "Good. Is the kitchen separate?"),
            ("A", "Yes, the kitchen is just here. It has a fridge, a cooker, and a washing machine."),
            ("B", "That's great. The kitchen looks new."),
            ("A", "Yes, we changed it last year. The bathroom is next to the kitchen."),
            ("B", "Okay. How much is the rent?"),
            ("A", "The rent is nine hundred dollars a month."),
            ("B", "Does that include the bills?"),
            ("A", "No, you pay the electricity and water bills separately. But the internet is free."),
            ("B", "I see. Is there any parking?"),
            ("A", "Yes, there's one parking space behind the building. It's free for you."),
            ("B", "Perfect. Actually, can I have a pet? I have a small cat."),
            ("A", "A cat is fine. But no big dogs, sorry."),
            ("B", "That's okay. When can I move in?"),
            ("A", "The apartment is free from the first of next month."),
            ("B", "Good. By the way, do I need to pay a deposit?"),
            ("A", "Yes, you pay one month's rent as a deposit. You get it back when you leave."),
            ("B", "I understand. I really like this apartment. Can I think about it tonight?"),
            ("A", "Of course. Call me tomorrow if you want it."),
            ("B", "Thank you very much. I'll call you tomorrow."),
            ("A", "Great. Have a good evening!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "There are ___ bedrooms in the apartment.", "options": None, "correct_answer": "two|2", "order": 1},
            {"type": "fill_blank", "prompt": "The rent is ___ dollars a month.", "options": None, "correct_answer": "nine hundred|900", "order": 2},
            {"type": "fill_blank", "prompt": "The kitchen has a fridge, a cooker, and a ___ machine.", "options": None, "correct_answer": "washing", "order": 3},
            {"type": "fill_blank", "prompt": "The apartment is free from the first of next ___.", "options": None, "correct_answer": "month", "order": 4},
            {"type": "fill_blank", "prompt": "The deposit is one month's ___.", "options": None, "correct_answer": "rent", "order": 5},
            {"type": "true_false", "prompt": "The living room is bright.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "The bills are included in the rent.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "The internet is free.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "The viewer can keep a big dog.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "There is one free parking space.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Why does the living room get a lot of sun?", "options": ["the windows face south", "it has big lights", "it's on the top floor"], "correct_answer": "the windows face south", "order": 11},
            {"type": "mcq", "prompt": "When did they change the kitchen?", "options": ["this year", "last year", "two years ago"], "correct_answer": "last year", "order": 12},
            {"type": "mcq", "prompt": "What pet can the viewer have?", "options": ["a big dog", "a small cat", "no pets"], "correct_answer": "a small cat", "order": 13},
            {"type": "mcq", "prompt": "What does the viewer pay separately?", "options": ["internet", "electricity and water", "parking"], "correct_answer": "electricity and water", "order": 14},
            {"type": "mcq", "prompt": "What will the viewer do tonight?", "options": ["sign the contract", "think about it", "move in"], "correct_answer": "think about it", "order": 15},
        ],
    },
    {
        "slug": "returning-an-item",
        "title": "Returning an Item",
        "level": "elementary",
        "speaker_names": {"A": "Assistant", "B": "Customer"},
        "turns": [
            ("B", "Excuse me, I'd like to return this jacket, please."),
            ("A", "Of course. Is there a problem with it?"),
            ("B", "Yes. I bought it last week, but it's too small. I need a bigger size."),
            ("A", "No problem. Do you have the receipt?"),
            ("B", "Yes, here it is."),
            ("A", "Thank you. You didn't wear it outside, right?"),
            ("B", "No, I only tried it on at home. The tags are still on it."),
            ("A", "Perfect. Would you like a bigger size, or your money back?"),
            ("B", "I'd like a bigger size, please. Do you have it in large?"),
            ("A", "Let me check. I'm sorry, large is sold out in this colour. We have it in black."),
            ("B", "Hmm. Actually, I don't really like black. Can I have my money back instead?"),
            ("A", "Of course. How did you pay?"),
            ("B", "I paid by card."),
            ("A", "Okay, I'll put the money back on your card. It takes about three days."),
            ("B", "Three days. That's fine. The jacket was forty dollars, right?"),
            ("A", "Yes, forty dollars. You'll get all of it back."),
            ("B", "Great. By the way, is this shirt on sale?"),
            ("A", "Yes, all the shirts are twenty percent off this week."),
            ("B", "Nice. Maybe I'll buy one. Where are the fitting rooms?"),
            ("A", "They're at the back, next to the shoes."),
            ("B", "Thank you. One more thing — what time do you close today?"),
            ("A", "We close at eight tonight."),
            ("B", "Good. Thank you for your help."),
            ("A", "You're welcome. Have a nice day!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants to return a ___.", "options": None, "correct_answer": "jacket", "order": 1},
            {"type": "fill_blank", "prompt": "The customer bought it ___ week.", "options": None, "correct_answer": "last", "order": 2},
            {"type": "fill_blank", "prompt": "The jacket was ___ dollars.", "options": None, "correct_answer": "forty|40", "order": 3},
            {"type": "fill_blank", "prompt": "The refund takes about ___ days.", "options": None, "correct_answer": "three|3", "order": 4},
            {"type": "fill_blank", "prompt": "The shirts are ___ percent off this week.", "options": None, "correct_answer": "twenty|20", "order": 5},
            {"type": "true_false", "prompt": "The jacket is too big.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The customer has the receipt.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The customer wore the jacket outside.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "Large is available in the customer's colour.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The customer paid by card.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "Why does the customer return the jacket?", "options": ["it's the wrong colour", "it's too small", "it's broken"], "correct_answer": "it's too small", "order": 11},
            {"type": "mcq", "prompt": "What does the customer decide in the end?", "options": ["a bigger size", "money back", "a different jacket"], "correct_answer": "money back", "order": 12},
            {"type": "mcq", "prompt": "How will the customer get the money?", "options": ["cash", "back on the card", "a gift card"], "correct_answer": "back on the card", "order": 13},
            {"type": "mcq", "prompt": "Why doesn't the customer take the black jacket?", "options": ["it's too expensive", "doesn't like black", "it's damaged"], "correct_answer": "doesn't like black", "order": 14},
            {"type": "mcq", "prompt": "Where are the fitting rooms?", "options": ["at the front", "at the back next to the shoes", "upstairs"], "correct_answer": "at the back next to the shoes", "order": 15},
        ],
    },
    {
        "slug": "calling-in-sick-to-work",
        "title": "Calling in Sick to Work",
        "level": "elementary",
        "speaker_names": {"A": "Manager", "B": "Employee"},
        "turns": [
            ("A", "Good morning, this is Karen speaking."),
            ("B", "Good morning, Karen. It's Daniel. I'm sorry, but I can't come to work today."),
            ("A", "Oh, I'm sorry to hear that. What's wrong?"),
            ("B", "I'm not feeling well. I have a high fever and a bad headache."),
            ("A", "That doesn't sound good. Did you see a doctor?"),
            ("B", "Not yet. I'm going to call the clinic this morning."),
            ("A", "Good idea. You should rest at home today."),
            ("B", "Thank you. I'm really sorry about the meeting at ten."),
            ("A", "Don't worry about the meeting. I can ask Lisa to take notes for you."),
            ("B", "Thank you, that's very kind. I'll read them tomorrow."),
            ("A", "Of course. Do you think you can come tomorrow?"),
            ("B", "I'm not sure. Maybe, but I want to see how I feel in the morning."),
            ("A", "That's fine. Your health is more important. Just send me a message tomorrow morning."),
            ("B", "I will. Actually, there's an email from a customer in my inbox. It's important."),
            ("A", "Don't worry. Can you tell me the customer's name? I'll answer it for you."),
            ("B", "Yes, it's Mr Brown. He's asking about his order."),
            ("A", "Okay, I'll take care of it. You just focus on getting better."),
            ("B", "Thank you so much, Karen. I really appreciate it."),
            ("A", "No problem at all. Take your medicine and drink a lot of water."),
            ("B", "I will. Thank you. By the way, do I need a doctor's note?"),
            ("A", "For one day, no. But for more than three days, please bring a note."),
            ("B", "Okay, I understand. Thank you again."),
            ("A", "Get well soon, Daniel. Bye for now."),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The employee's name is ___.", "options": None, "correct_answer": "Daniel", "order": 1},
            {"type": "fill_blank", "prompt": "The manager's name is ___.", "options": None, "correct_answer": "Karen", "order": 2},
            {"type": "fill_blank", "prompt": "The employee has a high ___ and a headache.", "options": None, "correct_answer": "fever", "order": 3},
            {"type": "fill_blank", "prompt": "The meeting is at ___.", "options": None, "correct_answer": "ten|10", "order": 4},
            {"type": "fill_blank", "prompt": "The customer's name is Mr ___.", "options": None, "correct_answer": "Brown", "order": 5},
            {"type": "true_false", "prompt": "Daniel can come to work today.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "Daniel already saw a doctor.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "Karen will ask Lisa to take notes.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "Karen will answer the customer's email.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Daniel needs a doctor's note for one day.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Why can't Daniel come to work?", "options": ["he's on holiday", "he's sick", "his car broke"], "correct_answer": "he's sick", "order": 11},
            {"type": "mcq", "prompt": "What is Daniel going to do this morning?", "options": ["come to work late", "call the clinic", "sleep"], "correct_answer": "call the clinic", "order": 12},
            {"type": "mcq", "prompt": "Who will take notes at the meeting?", "options": ["Karen", "Lisa", "Mr Brown"], "correct_answer": "Lisa", "order": 13},
            {"type": "mcq", "prompt": "What is the customer asking about?", "options": ["his order", "a refund", "a job"], "correct_answer": "his order", "order": 14},
            {"type": "mcq", "prompt": "When does Daniel need a doctor's note?", "options": ["for one day", "for more than three days", "never"], "correct_answer": "for more than three days", "order": 15},
        ],
    },
    {
        "slug": "inviting-a-friend-over-for-dinner",
        "title": "Inviting a Friend Over for Dinner",
        "level": "elementary",
        "speaker_names": {"A": "Emma", "B": "Sam"},
        "turns": [
            ("A", "Hi Sam! Are you free on Friday evening?"),
            ("B", "Hi Emma! Let me think. Yes, I'm free. Why?"),
            ("A", "I'm cooking dinner at my place. Would you like to come?"),
            ("B", "I'd love to! What time?"),
            ("A", "Come at seven. Is that okay for you?"),
            ("B", "Seven is perfect. What are you cooking?"),
            ("A", "I'm making a chicken curry. Do you like spicy food?"),
            ("B", "Yes, I love spicy food! But not too spicy, please."),
            ("A", "Don't worry, it's not very hot. Are you allergic to anything?"),
            ("B", "No, I can eat everything. Should I bring something?"),
            ("A", "You don't have to, but you can bring some drinks if you like."),
            ("B", "Okay, I'll bring some juice and a bottle of wine."),
            ("A", "Wonderful. My sister is coming too. You met her last year, remember?"),
            ("B", "Oh yes, Lily! She's really nice. It'll be good to see her again."),
            ("A", "Great. Actually, do you know how to get to my new flat?"),
            ("B", "Not really. You moved last month, right?"),
            ("A", "Yes. Take the number five bus and get off at the park. My building is just across the road."),
            ("B", "The number five bus, get off at the park. Got it."),
            ("A", "My flat number is twelve, on the second floor."),
            ("B", "Number twelve, second floor. Perfect."),
            ("A", "By the way, do you still have my phone number?"),
            ("B", "Yes, I have it. I'll call you if I get lost."),
            ("A", "Good. See you on Friday at seven!"),
            ("B", "See you then. Thank you for inviting me, Emma!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "Emma invites Sam for dinner on ___ evening.", "options": None, "correct_answer": "Friday", "order": 1},
            {"type": "fill_blank", "prompt": "Sam should come at ___ o'clock.", "options": None, "correct_answer": "seven|7", "order": 2},
            {"type": "fill_blank", "prompt": "Emma is making a chicken ___.", "options": None, "correct_answer": "curry", "order": 3},
            {"type": "fill_blank", "prompt": "Sam will take the number ___ bus.", "options": None, "correct_answer": "five|5", "order": 4},
            {"type": "fill_blank", "prompt": "Emma's flat number is ___.", "options": None, "correct_answer": "twelve|12", "order": 5},
            {"type": "true_false", "prompt": "Sam is free on Friday evening.", "options": None, "correct_answer": "True", "order": 6},
            {"type": "true_false", "prompt": "Sam doesn't like spicy food.", "options": None, "correct_answer": "False", "order": 7},
            {"type": "true_false", "prompt": "Sam is allergic to some food.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "Emma's sister Lily is coming too.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Emma's flat is on the first floor.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "What is Emma cooking?", "options": ["pizza", "chicken curry", "fish"], "correct_answer": "chicken curry", "order": 11},
            {"type": "mcq", "prompt": "What will Sam bring?", "options": ["nothing", "juice and wine", "dessert"], "correct_answer": "juice and wine", "order": 12},
            {"type": "mcq", "prompt": "Where should Sam get off the bus?", "options": ["at the park", "at the station", "at the shops"], "correct_answer": "at the park", "order": 13},
            {"type": "mcq", "prompt": "Who else is coming to dinner?", "options": ["Emma's sister", "Sam's brother", "no one"], "correct_answer": "Emma's sister", "order": 14},
            {"type": "mcq", "prompt": "What will Sam do if he gets lost?", "options": ["go home", "call Emma", "wait"], "correct_answer": "call Emma", "order": 15},
        ],
    },
    {
        "slug": "talking-about-your-weekend",
        "title": "Talking About Your Weekend",
        "level": "elementary",
        "speaker_names": {"A": "Anna", "B": "Tom"},
        "turns": [
            ("A", "Good morning, Tom! Did you have a good weekend?"),
            ("B", "Hi Anna! Yes, it was great, thank you. How about you?"),
            ("A", "It was nice and relaxing. What did you do?"),
            ("B", "On Saturday, I went hiking with some friends. The weather was perfect."),
            ("A", "That sounds wonderful! Where did you go?"),
            ("B", "We went to the mountains, about two hours from the city. We walked for four hours."),
            ("A", "Four hours! You must be tired."),
            ("B", "A little, but it was so beautiful. We took a lot of photos. And on Sunday, I just stayed home and rested."),
            ("A", "That sounds like a good balance. Did you cook?"),
            ("B", "Yes, I cooked a big lunch for my family. We had fish and vegetables."),
            ("A", "Delicious! My weekend was quieter. On Saturday I went shopping and bought some new shoes."),
            ("B", "Nice! And on Sunday?"),
            ("A", "On Sunday I visited my grandmother. She made the best cake. Actually, she gave me some to take home."),
            ("B", "That's lovely. Family time is the best."),
            ("A", "It really is. But the weekend was too short, as always!"),
            ("B", "I know! By the way, are you going to the team lunch on Friday?"),
            ("A", "Yes, I am! Are you?"),
            ("B", "Of course. I never miss free food!"),
            ("A", "Ha! Me too. Okay, let's get back to work."),
            ("B", "Yes, let's. Have a good day, Anna!"),
            ("A", "You too, Tom!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "On Saturday, Tom went ___ with friends.", "options": None, "correct_answer": "hiking", "order": 1},
            {"type": "fill_blank", "prompt": "They walked for ___ hours.", "options": None, "correct_answer": "four|4", "order": 2},
            {"type": "fill_blank", "prompt": "On Sunday, Tom cooked a big ___ for his family.", "options": None, "correct_answer": "lunch", "order": 3},
            {"type": "fill_blank", "prompt": "Anna bought some new ___ on Saturday.", "options": None, "correct_answer": "shoes", "order": 4},
            {"type": "fill_blank", "prompt": "On Sunday, Anna visited her ___.", "options": None, "correct_answer": "grandmother", "order": 5},
            {"type": "true_false", "prompt": "Tom had a bad weekend.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The weather was perfect for hiking.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "Tom stayed home on Sunday.", "options": None, "correct_answer": "True", "order": 8},
            {"type": "true_false", "prompt": "Anna's grandmother gave her some cake.", "options": None, "correct_answer": "True", "order": 9},
            {"type": "true_false", "prompt": "Tom will miss the team lunch on Friday.", "options": None, "correct_answer": "False", "order": 10},
            {"type": "mcq", "prompt": "Where did Tom go hiking?", "options": ["by the sea", "in the mountains", "in a park"], "correct_answer": "in the mountains", "order": 11},
            {"type": "mcq", "prompt": "What did Tom cook for his family?", "options": ["fish and vegetables", "pizza", "chicken"], "correct_answer": "fish and vegetables", "order": 12},
            {"type": "mcq", "prompt": "What did Anna do on Saturday?", "options": ["went hiking", "went shopping", "stayed home"], "correct_answer": "went shopping", "order": 13},
            {"type": "mcq", "prompt": "Who did Anna visit on Sunday?", "options": ["her grandmother", "her friend", "her sister"], "correct_answer": "her grandmother", "order": 14},
            {"type": "mcq", "prompt": "When is the team lunch?", "options": ["Wednesday", "Friday", "Monday"], "correct_answer": "Friday", "order": 15},
        ],
    },
    {
        "slug": "getting-a-haircut",
        "title": "Getting a Haircut",
        "level": "elementary",
        "speaker_names": {"A": "Hairdresser", "B": "Customer"},
        "turns": [
            ("A", "Hello! Welcome. Do you have an appointment?"),
            ("B", "No, I don't. Is that okay?"),
            ("A", "That's fine, we're not busy now. Please sit down. What would you like today?"),
            ("B", "I'd like a haircut, please. My hair is too long."),
            ("A", "Okay. How short would you like it?"),
            ("B", "Not too short. Just take a little off the top and the sides."),
            ("A", "No problem. Do you want me to wash it first?"),
            ("B", "Yes, please. A wash sounds nice."),
            ("A", "Great. The water is warm — tell me if it's too hot."),
            ("B", "It's perfect, thank you. Actually, can you make the sides a bit shorter?"),
            ("A", "Of course. Like this?"),
            ("B", "Yes, that's good. But please leave the top a little longer."),
            ("A", "No problem. Do you use any hair products?"),
            ("B", "Sometimes I use a little gel, but not every day."),
            ("A", "Okay. Your hair is very healthy. Do you want me to dry it after?"),
            ("B", "Yes, please. By the way, how much is a haircut here?"),
            ("A", "A haircut with a wash is twenty-five dollars."),
            ("B", "That's good. Are you open on weekends?"),
            ("A", "Yes, we're open every day except Monday."),
            ("B", "Good to know. I'll come back next month."),
            ("A", "Wonderful. Okay, all finished! What do you think?"),
            ("B", "Wow, it looks great! Thank you so much."),
            ("A", "You're welcome! Please pay at the desk. And come back soon!"),
            ("B", "I will. Thank you again!"),
        ],
        "questions": [
            {"type": "fill_blank", "prompt": "The customer wants a ___.", "options": None, "correct_answer": "haircut", "order": 1},
            {"type": "fill_blank", "prompt": "The customer's hair is too ___.", "options": None, "correct_answer": "long", "order": 2},
            {"type": "fill_blank", "prompt": "The hairdresser will wash and ___ the hair.", "options": None, "correct_answer": "dry", "order": 3},
            {"type": "fill_blank", "prompt": "A haircut with a wash costs ___ dollars.", "options": None, "correct_answer": "twenty-five|25", "order": 4},
            {"type": "fill_blank", "prompt": "The salon is closed on ___.", "options": None, "correct_answer": "Monday", "order": 5},
            {"type": "true_false", "prompt": "The customer has an appointment.", "options": None, "correct_answer": "False", "order": 6},
            {"type": "true_false", "prompt": "The customer wants a wash first.", "options": None, "correct_answer": "True", "order": 7},
            {"type": "true_false", "prompt": "The customer wants the top very short.", "options": None, "correct_answer": "False", "order": 8},
            {"type": "true_false", "prompt": "The customer uses gel every day.", "options": None, "correct_answer": "False", "order": 9},
            {"type": "true_false", "prompt": "The salon is open on weekends.", "options": None, "correct_answer": "True", "order": 10},
            {"type": "mcq", "prompt": "How short does the customer want the haircut?", "options": ["very short", "not too short", "shaved"], "correct_answer": "not too short", "order": 11},
            {"type": "mcq", "prompt": "What does the customer want for the sides?", "options": ["longer", "a bit shorter", "the same"], "correct_answer": "a bit shorter", "order": 12},
            {"type": "mcq", "prompt": "Does the customer want the hair washed?", "options": ["yes", "no", "only dried"], "correct_answer": "yes", "order": 13},
            {"type": "mcq", "prompt": "How often does the customer use gel?", "options": ["every day", "sometimes", "never"], "correct_answer": "sometimes", "order": 14},
            {"type": "mcq", "prompt": "When will the customer come back?", "options": ["next week", "next month", "next year"], "correct_answer": "next month", "order": 15},
        ],
    },
]


def build_transcript(turns: list[tuple[str, str]], speaker_names: dict[str, str]) -> str:
    return "\n".join(f"{speaker_names[speaker]}: {text}" for speaker, text in turns)


def main() -> None:
    db = SessionLocal()
    try:
        existing_titles = {a.title for a in db.query(ListeningAudio).all()}

        for lesson in LESSONS:
            if lesson["title"] in existing_titles:
                print(f"--- Skipping '{lesson['slug']}' (already seeded) ---")
                continue

            print(f"--- Generating audio for '{lesson['slug']}' (level={lesson['level']}) ---")
            audio_url = generate_lesson_audio(lesson["turns"], lesson["slug"], lesson["level"])
            print(f"  audio: {audio_url}")

            speaker_names = lesson.get("speaker_names", DEFAULT_SPEAKER_NAMES)
            audio = ListeningAudio(
                title=lesson["title"],
                level=lesson["level"],
                transcript=build_transcript(lesson["turns"], speaker_names),
                audio_url=audio_url,
            )
            db.add(audio)
            db.flush()  # assign audio.id before inserting questions

            for q in lesson["questions"]:
                db.add(
                    ListeningQuestion(
                        audio_id=audio.id,
                        type=q["type"],
                        prompt=q["prompt"],
                        options=q["options"],
                        correct_answer=q["correct_answer"],
                        order=q["order"],
                    )
                )

            db.commit()
            print(f"  Inserted ListeningAudio id={audio.id} with {len(lesson['questions'])} question(s)\n")

        print("Done.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
